export const INITIAL_HOSPITALS = [
  {
    id: 'hosp-1',
    name: 'Apollo Hospital',
    registrationNo: 'MH-MUM-2018-8821',
    authorizedPerson: 'Dr. Rajesh Sharma (Chief Pharmacist)',
    email: 'apollo.mumbai@smartmedishare.org',
    phone: '+91 98201 54321',
    address: 'Plot No. 13, Sector 23, Off CBD Belapur Road',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400614',
    status: 'verified',
    registeredDate: '2024-01-15',
    verifiedDate: '2024-01-16',
    documents: [
      { name: 'Hospital_Registration_Cert.pdf', size: '2.4 MB', type: 'Registration Certificate', verified: true },
      { name: 'Drug_License_Form20B_21B.pdf', size: '3.1 MB', type: 'Drug License', verified: true },
      { name: 'GST_Registration_Certificate.pdf', size: '1.2 MB', type: 'GST Certificate', verified: true },
      { name: 'Director_Authorization_Letter.pdf', size: '1.8 MB', type: 'Authorization Letter', verified: true },
    ],
  },
  {
    id: 'hosp-2',
    name: 'Fortis Memorial Research Institute',
    registrationNo: 'HR-GUR-2019-4412',
    authorizedPerson: 'Dr. Sunita Deshmukh (Procurement Lead)',
    email: 'fortis.gurgaon@smartmedishare.org',
    phone: '+91 98112 33445',
    address: 'Sector 44, Opposite HUDA City Centre Metro',
    city: 'Gurgaon',
    state: 'Haryana',
    pincode: '122002',
    status: 'verified',
    registeredDate: '2024-02-10',
    verifiedDate: '2024-02-12',
    documents: [
      { name: 'Fortis_Hospital_Reg.pdf', size: '4.2 MB', type: 'Registration Certificate', verified: true },
      { name: 'Pharmacy_Retail_Wholesale_Lic.pdf', size: '2.8 MB', type: 'Drug License', verified: true },
      { name: 'GST_Compliance_2024.pdf', size: '1.5 MB', type: 'GST Certificate', verified: true },
      { name: 'Board_Resolution_MediShare.pdf', size: '1.1 MB', type: 'Authorization Letter', verified: true },
    ],
  },
  {
    id: 'hosp-3',
    name: 'Max Super Speciality Hospital',
    registrationNo: 'DL-SAK-2020-9011',
    authorizedPerson: 'Dr. Amitav Roy (Director Operations)',
    email: 'max.saket@smartmedishare.org',
    phone: '+91 99100 87654',
    address: '1, 2, Press Enclave Marg, Saket',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110017',
    status: 'verified',
    registeredDate: '2024-03-05',
    verifiedDate: '2024-03-07',
    documents: [
      { name: 'Max_Health_RegDoc.pdf', size: '3.6 MB', type: 'Registration Certificate', verified: true },
      { name: 'Drug_Inspector_Approved_Lic.pdf', size: '2.9 MB', type: 'Drug License', verified: true },
      { name: 'GST_Saket_Max.pdf', size: '1.4 MB', type: 'GST Certificate', verified: true },
      { name: 'Authorized_Signatory_Roy.pdf', size: '1.9 MB', type: 'Authorization Letter', verified: true },
    ],
  },
  {
    id: 'hosp-4',
    name: 'Manipal Hospital',
    registrationNo: 'KA-BLR-2021-3320',
    authorizedPerson: 'Dr. Anand Kumar (Head of Inventory)',
    email: 'manipal.blr@smartmedishare.org',
    phone: '+91 97411 22334',
    address: '98, HAL Old Airport Rd, Kodihalli',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560017',
    status: 'pending',
    registeredDate: '2024-08-28',
    verifiedDate: null,
    documents: [
      { name: 'Manipal_Establishment_Act_Doc.pdf', size: '5.1 MB', type: 'Registration Certificate', verified: false },
      { name: 'Form20_Pharmacy_Permit.pdf', size: '3.4 MB', type: 'Drug License', verified: false },
      { name: 'Karnataka_GST_Manipal.pdf', size: '1.7 MB', type: 'GST Certificate', verified: false },
      { name: 'MD_Power_of_Attorney.pdf', size: '2.2 MB', type: 'Authorization Letter', verified: false },
    ],
  },
  {
    id: 'hosp-5',
    name: 'Lilavati Hospital & Research Centre',
    registrationNo: 'MH-MUM-2017-1099',
    authorizedPerson: 'Dr. Priya Merchant (Pharmacy Head)',
    email: 'lilavati.mumbai@smartmedishare.org',
    phone: '+91 98211 44556',
    address: 'A-791, Bandra Reclamation, Bandra West',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400050',
    status: 'pending',
    registeredDate: '2024-08-30',
    verifiedDate: null,
    documents: [
      { name: 'Lilavati_Registration_Doc.pdf', size: '4.8 MB', type: 'Registration Certificate', verified: false },
      { name: 'Drug_Authority_Approval.pdf', size: '2.6 MB', type: 'Drug License', verified: false },
      { name: 'GSTIN_MH_Lilavati.pdf', size: '1.3 MB', type: 'GST Certificate', verified: false },
      { name: 'Authorization_DrMerchant.pdf', size: '1.5 MB', type: 'Authorization Letter', verified: false },
    ],
  },
  {
    id: 'hosp-6',
    name: 'Medanta - The Medicity',
    registrationNo: 'HR-GUR-2022-7714',
    authorizedPerson: 'Dr. Vikram Malhotra (Medical Superintendent)',
    email: 'medanta.gurgaon@smartmedishare.org',
    phone: '+91 99990 11223',
    address: 'CH Bakhtawar Singh Rd, Sector 38',
    city: 'Gurgaon',
    state: 'Haryana',
    pincode: '122001',
    status: 'rejected',
    registeredDate: '2024-08-15',
    verifiedDate: null,
    rejectionReason: 'GST document expired and drug storage temperature logs missing for schedule H1 compliance.',
    documents: [
      { name: 'Medanta_Reg_Old.pdf', size: '3.1 MB', type: 'Registration Certificate', verified: false },
      { name: 'Drug_Lic_2022.pdf', size: '2.0 MB', type: 'Drug License', verified: false },
    ],
  },
  {
    id: 'hosp-7',
    name: 'Tata Memorial Centre',
    registrationNo: 'MH-MUM-2016-5501',
    authorizedPerson: 'Dr. Sudeep Gupta (Director & Chief Oncologist)',
    email: 'tatamemorial.mumbai@smartmedishare.org',
    phone: '+91 98200 99881',
    address: 'Dr. E Borges Road, Parel',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400012',
    status: 'verified',
    registeredDate: '2024-02-01',
    verifiedDate: '2024-02-03',
    documents: [
      { name: 'TMC_Statutory_Reg_2024.pdf', size: '5.4 MB', type: 'Registration Certificate', verified: true },
      { name: 'Oncology_Form20B_Permit.pdf', size: '3.8 MB', type: 'Drug License', verified: true },
      { name: 'Atomic_Energy_Regulatory_Lic.pdf', size: '4.1 MB', type: 'Nuclear Medicine License', verified: true },
    ],
  },
  {
    id: 'hosp-8',
    name: 'All India Institute of Medical Sciences (AIIMS)',
    registrationNo: 'DL-DEL-2015-0001',
    authorizedPerson: 'Dr. M. Srinivas (Director & Central Pharmacy Head)',
    email: 'aiims.delhi@smartmedishare.org',
    phone: '+91 98101 11223',
    address: 'Sri Aurobindo Marg, Ansari Nagar East',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110029',
    status: 'verified',
    registeredDate: '2024-01-10',
    verifiedDate: '2024-01-11',
    documents: [
      { name: 'AIIMS_Parliament_Charter.pdf', size: '6.2 MB', type: 'Registration Certificate', verified: true },
      { name: 'Central_Drugs_Standard_Lic.pdf', size: '4.5 MB', type: 'Drug License', verified: true },
      { name: 'Form21B_Wholesale_Dossier.pdf', size: '3.2 MB', type: 'Drug License', verified: true },
    ],
  },
  {
    id: 'hosp-9',
    name: 'Kokilaben Dhirubhai Ambani Hospital',
    registrationNo: 'MH-MUM-2019-7819',
    authorizedPerson: 'Dr. Santosh Shetty (Executive Director)',
    email: 'kokilaben.mumbai@smartmedishare.org',
    phone: '+91 98330 44556',
    address: 'Rao Saheb, Achutrao Patwardhan Marg, Four Bungalows, Andheri West',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400053',
    status: 'verified',
    registeredDate: '2024-03-12',
    verifiedDate: '2024-03-14',
    documents: [
      { name: 'KDAH_Accreditation_Certificate.pdf', size: '4.1 MB', type: 'Registration Certificate', verified: true },
      { name: 'NABH_Pharmacy_Compliance.pdf', size: '2.9 MB', type: 'Drug License', verified: true },
    ],
  },
  {
    id: 'hosp-10',
    name: 'Christian Medical College (CMC)',
    registrationNo: 'TN-VEL-2018-3419',
    authorizedPerson: 'Dr. Vikram Mathews (Medical Superintendent)',
    email: 'cmc.vellore@smartmedishare.org',
    phone: '+91 94430 77889',
    address: 'Ida Scudder Road',
    city: 'Vellore',
    state: 'Tamil Nadu',
    pincode: '632004',
    status: 'under_review',
    registeredDate: '2024-08-20',
    verifiedDate: null,
    reviewNote: 'Statutory audit team reviewing cold-chain IoT temperature datalogs for Schedule X drugs.',
    documents: [
      { name: 'CMC_Establishment_Doc.pdf', size: '4.9 MB', type: 'Registration Certificate', verified: false },
      { name: 'Form20B_Retail_Wholesale.pdf', size: '3.3 MB', type: 'Drug License', verified: false },
    ],
  },
  {
    id: 'hosp-11',
    name: 'PGIMER Chandigarh',
    registrationNo: 'CH-CHD-2017-9102',
    authorizedPerson: 'Dr. Vivek Lal (Director & Head of Pharmacy)',
    email: 'pgimer.chd@smartmedishare.org',
    phone: '+91 98760 12345',
    address: 'Sector 12',
    city: 'Chandigarh',
    state: 'Chandigarh',
    pincode: '160012',
    status: 'documents_missing',
    registeredDate: '2024-08-22',
    verifiedDate: null,
    reviewNote: 'Form 21B drug wholesale license endorsement page 3 missing authorized signatory seal.',
    documents: [
      { name: 'PGIMER_Registration.pdf', size: '5.0 MB', type: 'Registration Certificate', verified: false },
      { name: 'Drug_License_Page1_Only.pdf', size: '1.2 MB', type: 'Drug License', verified: false },
    ],
  },
  {
    id: 'hosp-12',
    name: 'Sir Ganga Ram Hospital',
    registrationNo: 'DL-DEL-2016-4488',
    authorizedPerson: 'Dr. Ajay Swaroop (Board of Management)',
    email: 'gangaram.delhi@smartmedishare.org',
    phone: '+91 98110 55667',
    address: 'Sir Ganga Ram Hospital Marg, Old Rajinder Nagar',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110060',
    status: 'verified',
    registeredDate: '2024-04-18',
    verifiedDate: '2024-04-20',
    documents: [
      { name: 'SGRH_Society_Registration.pdf', size: '4.3 MB', type: 'Registration Certificate', verified: true },
      { name: 'Delhi_State_Pharmacy_License.pdf', size: '3.1 MB', type: 'Drug License', verified: true },
    ],
  },
  {
    id: 'hosp-13',
    name: 'Sanjeevani Multispeciality Hospital',
    registrationNo: 'MH-PUN-2021-9988',
    authorizedPerson: 'Dr. Ramesh Kulkarni (Medical Superintendent)',
    email: 'sanjeevani.pune@smartmedishare.org',
    phone: '+91 98230 77889',
    address: 'Near Deccan Gymkhana, Shivaji Nagar',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411004',
    status: 'suspended',
    registeredDate: '2024-03-22',
    verifiedDate: '2024-03-24',
    suspensionReason: 'Cold-chain storage failure detected during regulatory inspection; operations quarantined.',
    documents: [
      { id: 'doc-hosp-13-1', hospitalId: 'hosp-13', name: 'Sanjeevani_Hospital_Reg.pdf', documentName: 'Sanjeevani_Hospital_Reg.pdf', type: 'Registration Certificate', documentType: 'Registration Certificate', size: '3.5 MB', verified: true, documentStatus: 'verified', uploadedAt: '2024-03-22', reviewedAt: '2024-03-24' },
      { id: 'doc-hosp-13-2', hospitalId: 'hosp-13', name: 'Drug_License_Form20B.pdf', documentName: 'Drug_License_Form20B.pdf', type: 'Drug License', documentType: 'Drug License', size: '2.8 MB', verified: false, documentStatus: 'rejected', rejectionReason: 'Cold-chain endorsement revoked by drug inspector.', uploadedAt: '2024-03-22', reviewedAt: '2024-08-10' },
    ],
  }
];

export const INITIAL_MEDICINES = [
  {
    id: 'med-101',
    brandName: 'Meropenem Injection',
    genericName: 'Meropenem Trihydrate IP',
    power: '1g IV Vial',
    category: 'Critical Care / Antibiotic',
    storageType: 'Cold Storage (2°C - 8°C)',
    mfgDate: '2023-11-20',
    expiryDate: '2024-11-20',
    batchNo: 'MP23G418',
    manufacturer: 'AstraZeneca Healthcare',
    quantity: 45,
    unitOriginalPrice: 1850,
    concessionPercent: 35,
    hospitalId: 'hosp-2',
    hospitalName: 'Fortis Memorial Research Institute',
    location: 'Gurgaon, Haryana',
    distanceKm: 14.5,
    dateAdded: '2024-08-01',
    notes: 'Stored in certified cold chain facility, seal intact.',
  },
  {
    id: 'med-102',
    brandName: 'Enoxaparin Sodium',
    genericName: 'Clexane Anti-coagulant',
    power: '40mg / 0.4ml Prefilled Syringe',
    category: 'Cardiology / Hematology',
    storageType: 'Room Temperature (15°C - 25°C)',
    mfgDate: '2023-12-15',
    expiryDate: '2024-12-15',
    batchNo: 'CX88902',
    manufacturer: 'Sanofi India Ltd',
    quantity: 120,
    unitOriginalPrice: 480,
    concessionPercent: 25,
    hospitalId: 'hosp-3',
    hospitalName: 'Max Super Speciality Hospital',
    location: 'New Delhi, Delhi',
    distanceKm: 22.0,
    dateAdded: '2024-08-05',
    notes: 'Surplus surgical inventory from cardiac unit.',
  },
  {
    id: 'med-103',
    brandName: 'Human Albumin 20%',
    genericName: 'Human Albumin Solution USP',
    power: '100ml Infusion Bottle',
    category: 'Emergency / Plasma expander',
    storageType: 'Room Temperature (2°C - 25°C)',
    mfgDate: '2024-01-30',
    expiryDate: '2025-01-30',
    batchNo: 'ALB9941',
    manufacturer: 'Baxter Healthcare',
    quantity: 28,
    unitOriginalPrice: 4200,
    concessionPercent: 20,
    hospitalId: 'hosp-2',
    hospitalName: 'Fortis Memorial Research Institute',
    location: 'Gurgaon, Haryana',
    distanceKm: 14.5,
    dateAdded: '2024-08-10',
    notes: 'High demand plasma derivative.',
  },
  {
    id: 'med-104',
    brandName: 'Augmentin Duo',
    genericName: 'Amoxicillin + Potassium Clavulanate',
    power: '625mg Tablets (Strip of 10)',
    category: 'General / Antibiotic',
    storageType: 'Dry & Cool (<25°C)',
    mfgDate: '2024-04-15',
    expiryDate: '2025-04-15',
    batchNo: 'AG625-78',
    manufacturer: 'GlaxoSmithKline',
    quantity: 350,
    unitOriginalPrice: 210,
    concessionPercent: 15,
    hospitalId: 'hosp-3',
    hospitalName: 'Max Super Speciality Hospital',
    location: 'New Delhi, Delhi',
    distanceKm: 22.0,
    dateAdded: '2024-08-12',
    notes: 'Standard hospital pharmacy stock.',
  },
  {
    id: 'med-105',
    brandName: 'Augmentin Duo 625mg',
    genericName: 'Amoxicillin + Potassium Clavulanate IP',
    power: '625mg Tablets',
    form: 'Tablet',
    category: 'Critical Care / Antibiotic',
    storageType: 'Room Temperature (15°C - 25°C)',
    mfgDate: new Date(Date.now() - 100 * 86400000).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 240 * 86400000).toISOString().split('T')[0],
    batchNo: 'AUG-625-91',
    manufacturer: 'GlaxoSmithKline Pharma',
    quantity: 250,
    minStockLevel: 30,
    unitOriginalPrice: 210,
    concessionPercent: 15,
    hospitalId: 'hosp-1',
    hospitalName: 'Apollo Hospital',
    location: 'Mumbai, Maharashtra',
    distanceKm: 0,
    dateAdded: '2024-07-20',
    notes: 'Standard verified hospital inventory.',
  },
  {
    id: 'med-106',
    brandName: 'Insulin Glargine (Lantus)',
    genericName: 'Insulin Glargine 100 IU/ml',
    power: '3ml SoloStar Pen',
    form: 'Pre-filled Syringe / Pen',
    category: 'Diabetes Care',
    storageType: 'Cold Storage (2°C - 8°C)',
    mfgDate: new Date(Date.now() - 400 * 86400000).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() - 35 * 86400000).toISOString().split('T')[0], // Expired 35 days ago
    batchNo: 'LT-EXP-908',
    manufacturer: 'Sanofi Healthcare',
    quantity: 40,
    minStockLevel: 15,
    unitOriginalPrice: 890,
    concessionPercent: 0,
    hospitalId: 'hosp-1',
    hospitalName: 'Apollo Hospital',
    location: 'Mumbai, Maharashtra',
    distanceKm: 0,
    dateAdded: '2024-07-25',
    notes: 'Expired stock designated for Bio-Waste Disposal.',
  },
  {
    id: 'med-107',
    brandName: 'Ceftriaxone Injection (Monocef)',
    genericName: 'Ceftriaxone Sodium Sterile IP',
    power: '1000mg (1g) with WFI',
    form: 'Injection / Vial',
    category: 'Critical Care / Antibiotic',
    storageType: 'Room Temperature (15°C - 30°C)',
    mfgDate: new Date(Date.now() - 60 * 86400000).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 180 * 86400000).toISOString().split('T')[0],
    batchNo: 'MC1000-88',
    manufacturer: 'Aristo Pharmaceuticals',
    quantity: 450,
    minStockLevel: 50,
    unitOriginalPrice: 75,
    concessionPercent: 12,
    hospitalId: 'hosp-1',
    hospitalName: 'Apollo Hospital',
    location: 'Mumbai, Maharashtra',
    distanceKm: 0,
    dateAdded: '2024-08-02',
    notes: 'High turnover antibiotic stock in outpatient bay.',
  },
  {
    id: 'med-108',
    brandName: 'Remdesivir IV (Covifor)',
    genericName: 'Remdesivir Lyophilized Powder',
    power: '100mg Vial',
    category: 'Antiviral / Emergency',
    storageType: 'Room Temperature (<30°C)',
    mfgDate: '2023-10-10',
    expiryDate: '2024-10-10',
    batchNo: 'RDV-401',
    manufacturer: 'Hetero Healthcare',
    quantity: 35,
    unitOriginalPrice: 2800,
    concessionPercent: 45,
    hospitalId: 'hosp-2',
    hospitalName: 'Fortis Memorial Research Institute',
    location: 'Gurgaon, Haryana',
    distanceKm: 14.5,
    dateAdded: '2024-08-14',
    notes: 'Expiring in under 2 months, urgent redistribution.',
  },
  {
    id: 'med-109',
    brandName: 'Trastuzumab (Herclon)',
    genericName: 'Trastuzumab 440mg Lyophilized',
    power: '440mg Multi-dose Vial',
    category: 'Oncology',
    storageType: 'Cold Storage (2°C - 8°C)',
    mfgDate: '2024-02-28',
    expiryDate: '2025-02-28',
    batchNo: 'TRAST-991',
    manufacturer: 'Roche Products India',
    quantity: 8,
    unitOriginalPrice: 54000,
    concessionPercent: 20,
    hospitalId: 'hosp-3',
    hospitalName: 'Max Super Speciality Hospital',
    location: 'New Delhi, Delhi',
    distanceKm: 22.0,
    dateAdded: '2024-08-18',
    notes: 'Premium oncology monoclonal antibody.',
  },
  {
    id: 'med-110',
    brandName: 'Meropenem Injection',
    genericName: 'Meropenem Trihydrate IP',
    power: '1g IV Vial',
    form: 'Injection / Vial',
    category: 'Critical Care / Antibiotic',
    storageType: 'Cold Storage (2°C - 8°C)',
    mfgDate: new Date(Date.now() - 365 * 86400000).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() - 18 * 86400000).toISOString().split('T')[0], // Expired 18 days ago
    batchNo: 'MP-EXP-4401',
    manufacturer: 'AstraZeneca Healthcare',
    quantity: 60,
    minStockLevel: 20,
    unitOriginalPrice: 1850,
    concessionPercent: 0,
    hospitalId: 'hosp-1',
    hospitalName: 'Apollo Hospital',
    location: 'Mumbai, Maharashtra',
    distanceKm: 0,
    dateAdded: '2024-08-11',
    notes: 'Expired ICU stock flagged for Bio-Waste Disposal.',
  },
  {
    id: 'med-111',
    brandName: 'Dexamethasone Sodium Phosphate',
    genericName: 'Dexamethasone Inj 4mg/ml',
    power: '2ml Vial (Box of 20)',
    category: 'Steroids / Anti-inflammatory',
    storageType: 'Room Temperature (15°C - 30°C)',
    mfgDate: '2024-07-15',
    expiryDate: '2025-07-15',
    batchNo: 'DEX-092',
    manufacturer: 'Cadila Healthcare (Zydus)',
    quantity: 400,
    unitOriginalPrice: 140,
    concessionPercent: 15,
    hospitalId: 'hosp-2',
    hospitalName: 'Fortis Memorial Research Institute',
    location: 'Gurgaon, Haryana',
    distanceKm: 14.5,
    dateAdded: '2024-08-19',
    notes: 'Long-dated stable corticosteroid batch.',
  },
  {
    id: 'med-112',
    brandName: 'Paracetamol IV Infusion',
    genericName: 'Paracetamol 1% w/v IV',
    power: '100ml Infusion Bottle',
    category: 'Analgesics / Antipyretic',
    storageType: 'Room Temperature (<30°C)',
    mfgDate: '2024-05-10',
    expiryDate: '2025-05-10',
    batchNo: 'PCM-1008',
    manufacturer: 'Intas Pharmaceuticals',
    quantity: 650,
    unitOriginalPrice: 42,
    concessionPercent: 18,
    hospitalId: 'hosp-3',
    hospitalName: 'Max Super Speciality Hospital',
    location: 'New Delhi, Delhi',
    distanceKm: 22.0,
    dateAdded: '2024-08-20',
    notes: 'High volume standard infusion bottles.',
  },
  {
    id: 'med-113',
    brandName: 'Propofol Injection 1%',
    genericName: 'Propofol Injectable Emulsion 10mg/ml',
    power: '20ml Single-Dose Vial',
    category: 'Anesthesia / Critical Care',
    storageType: 'Room Temperature (4°C - 25°C)',
    mfgDate: '2024-01-10',
    expiryDate: new Date(Date.now() + 45 * 86400000).toISOString().split('T')[0], // 45 days left
    batchNo: 'PRF-4418',
    manufacturer: 'Fresenius Kabi India',
    quantity: 140,
    unitOriginalPrice: 380,
    concessionPercent: 35,
    hospitalId: 'hosp-5',
    hospitalName: 'Lilavati Hospital & Research Centre',
    location: 'Mumbai, Maharashtra',
    distanceKm: 8.5,
    dateAdded: '2024-08-22',
    notes: 'OT surgical surplus emulsion, near-expiry concession applied.',
  },
  {
    id: 'med-114',
    brandName: 'Atracurium Besylate Injection',
    genericName: 'Atracurium Besylate 10mg/ml',
    power: '2.5ml Ampoule (Pack of 5)',
    category: 'Anesthesia / Muscle Relaxant',
    storageType: 'Cold Storage (2°C - 8°C)',
    mfgDate: '2023-12-05',
    expiryDate: new Date(Date.now() + 32 * 86400000).toISOString().split('T')[0], // 32 days left
    batchNo: 'ATR-902',
    manufacturer: 'GlaxoSmithKline Pharmaceuticals',
    quantity: 75,
    unitOriginalPrice: 490,
    concessionPercent: 40,
    hospitalId: 'hosp-5',
    hospitalName: 'Lilavati Hospital & Research Centre',
    location: 'Mumbai, Maharashtra',
    distanceKm: 8.5,
    dateAdded: '2024-08-24',
    notes: 'Monitored under cold-chain compliance. Urgent redistribution.',
  },
  {
    id: 'med-115',
    brandName: 'Rituximab (Ristova) 500mg',
    genericName: 'Rituximab Concentrate for Solution for Infusion',
    power: '500mg / 50ml Vial',
    category: 'Oncology / Lymphoma',
    storageType: 'Cold Storage (2°C - 8°C)',
    mfgDate: '2024-03-01',
    expiryDate: '2025-09-01',
    batchNo: 'RTX-8841',
    manufacturer: 'Roche Products India',
    quantity: 12,
    unitOriginalPrice: 82000,
    concessionPercent: 25,
    hospitalId: 'hosp-7',
    hospitalName: 'Tata Memorial Centre',
    location: 'Mumbai, Maharashtra',
    distanceKm: 12.0,
    dateAdded: '2024-08-20',
    notes: 'Targeted monoclonal antibody for B-cell non-Hodgkin lymphoma.',
  },
  {
    id: 'med-116',
    brandName: 'Piperacillin + Tazobactam 4.5g',
    genericName: 'Piperacillin and Tazobactam for Injection USP',
    power: '4.5g IV Infusion Vial',
    category: 'Critical Care / Antibiotic',
    storageType: 'Room Temperature (20°C - 25°C)',
    mfgDate: '2024-04-12',
    expiryDate: '2025-10-12',
    batchNo: 'PTZ-6610',
    manufacturer: 'Pfizer Products India',
    quantity: 320,
    unitOriginalPrice: 460,
    concessionPercent: 20,
    hospitalId: 'hosp-7',
    hospitalName: 'Tata Memorial Centre',
    location: 'Mumbai, Maharashtra',
    distanceKm: 12.0,
    dateAdded: '2024-08-21',
    notes: 'Broad-spectrum beta-lactamase inhibitor for severe hospital-acquired infections.',
  },
  {
    id: 'med-117',
    brandName: 'Tacrolimus 1mg (Pangraf)',
    genericName: 'Tacrolimus Capsules USP 1mg',
    power: '1mg Hard Gelatin Capsules (Strip of 10)',
    category: 'Nephrology / Organ Transplant',
    storageType: 'Room Temperature (15°C - 25°C)',
    mfgDate: '2024-02-18',
    expiryDate: '2025-08-18',
    batchNo: 'TAC-1092',
    manufacturer: 'Biocon Biologics',
    quantity: 190,
    unitOriginalPrice: 720,
    concessionPercent: 22,
    hospitalId: 'hosp-8',
    hospitalName: 'All India Institute of Medical Sciences (AIIMS)',
    location: 'New Delhi, Delhi',
    distanceKm: 0,
    dateAdded: '2024-08-18',
    notes: 'Post-renal and liver transplant immunosuppressant maintenance.',
  },
  {
    id: 'med-118',
    brandName: 'Bevacizumab (Avastin) 400mg',
    genericName: 'Bevacizumab Solution for Infusion',
    power: '400mg / 16ml Vial',
    category: 'Oncology / Anti-Angiogenic',
    storageType: 'Cold Storage (2°C - 8°C)',
    mfgDate: '2024-01-25',
    expiryDate: '2025-07-25',
    batchNo: 'BVZ-7712',
    manufacturer: 'Roche Products India',
    quantity: 15,
    unitOriginalPrice: 65000,
    concessionPercent: 30,
    hospitalId: 'hosp-7',
    hospitalName: 'Tata Memorial Centre',
    location: 'Mumbai, Maharashtra',
    distanceKm: 12.0,
    dateAdded: '2024-08-25',
    notes: 'Certified cold-storage chain verified under Schedule C compliance.',
  },
  {
    id: 'med-119',
    brandName: 'Furosemide Injection (Lasix)',
    genericName: 'Furosemide Injection IP 10mg/ml',
    power: '2ml Ampoule (Box of 25)',
    category: 'Cardiology / Diuretic',
    storageType: 'Protect from Light (15°C - 30°C)',
    mfgDate: '2024-06-01',
    expiryDate: '2026-06-01',
    batchNo: 'LSX-3301',
    manufacturer: 'Sanofi India Ltd',
    quantity: 450,
    unitOriginalPrice: 85,
    concessionPercent: 10,
    hospitalId: 'hosp-9',
    hospitalName: 'Kokilaben Dhirubhai Ambani Hospital',
    location: 'Mumbai, Maharashtra',
    distanceKm: 6.2,
    dateAdded: '2024-08-26',
    notes: 'Standard CCU diuretic for acute pulmonary edema management.',
  },
  {
    id: 'med-120',
    brandName: 'Heparin Sodium 25,000 IU',
    genericName: 'Heparin Sodium Injection IP',
    power: '5ml Multi-Dose Vial',
    category: 'Cardiology / Anticoagulant',
    storageType: 'Room Temperature (20°C - 25°C)',
    mfgDate: '2024-03-15',
    expiryDate: '2025-09-15',
    batchNo: 'HEP-25K',
    manufacturer: 'Gland Pharma Ltd',
    quantity: 110,
    unitOriginalPrice: 520,
    concessionPercent: 25,
    hospitalId: 'hosp-9',
    hospitalName: 'Kokilaben Dhirubhai Ambani Hospital',
    location: 'Mumbai, Maharashtra',
    distanceKm: 6.2,
    dateAdded: '2024-08-26',
    notes: 'Hemodialysis and deep vein thrombosis prophylaxis stock.',
  },
  {
    id: 'med-121',
    brandName: 'Linezolid 600mg IV Infusion (Lizomac)',
    genericName: 'Linezolid IV 2mg/ml Infusion',
    power: '300ml IV Poly Infusion Bag',
    category: 'Critical Care / Oxazolidinone',
    storageType: 'Protect from Light (15°C - 30°C)',
    mfgDate: '2024-05-20',
    expiryDate: '2025-11-20',
    batchNo: 'LNZ-600',
    manufacturer: 'Macleods Pharmaceuticals',
    quantity: 210,
    unitOriginalPrice: 340,
    concessionPercent: 18,
    hospitalId: 'hosp-8',
    hospitalName: 'All India Institute of Medical Sciences (AIIMS)',
    location: 'New Delhi, Delhi',
    distanceKm: 0,
    dateAdded: '2024-08-23',
    notes: 'MRSA and Vancomycin-resistant enterococcal infection coverage.',
  },
  {
    id: 'med-122',
    brandName: 'Liposomal Amphotericin B 50mg (AmBisome)',
    genericName: 'Amphotericin B Liposome for Injection',
    power: '50mg Lyophilized Cake for Reconstitution',
    category: 'Infectious Disease / Antifungal',
    storageType: 'Cold Storage (2°C - 8°C)',
    mfgDate: '2024-02-10',
    expiryDate: '2025-08-10',
    batchNo: 'AMB-50L',
    manufacturer: 'Gilead / Mylan India',
    quantity: 40,
    unitOriginalPrice: 6200,
    concessionPercent: 25,
    hospitalId: 'hosp-8',
    hospitalName: 'All India Institute of Medical Sciences (AIIMS)',
    location: 'New Delhi, Delhi',
    distanceKm: 0,
    dateAdded: '2024-08-22',
    notes: 'Life-saving antifungal for invasive mucormycosis and candidiasis.',
  },
  {
    id: 'med-123',
    brandName: 'Octreotide Acetate 100mcg (Sandostatin)',
    genericName: 'Octreotide Solution for Injection',
    power: '1ml Ampoule (Box of 5)',
    category: 'Gastroenterology / Emergency',
    storageType: 'Cold Storage (2°C - 8°C)',
    mfgDate: '2024-01-18',
    expiryDate: '2025-07-18',
    batchNo: 'OCT-100',
    manufacturer: 'Novartis Healthcare',
    quantity: 60,
    unitOriginalPrice: 1450,
    concessionPercent: 30,
    hospitalId: 'hosp-5',
    hospitalName: 'Lilavati Hospital & Research Centre',
    location: 'Mumbai, Maharashtra',
    distanceKm: 8.5,
    dateAdded: '2024-08-27',
    notes: 'Bleeding esophageal varices emergency buffer supply.',
  },
  {
    id: 'med-124',
    brandName: 'Colistimethate Sodium 1 MIU (Xylistin)',
    genericName: 'Colistimethate Sodium for Injection IP',
    power: '1,000,000 IU Vial with WFI',
    category: 'Critical Care / Polymyxin',
    storageType: 'Room Temperature (<25°C)',
    mfgDate: '2024-04-05',
    expiryDate: '2025-10-05',
    batchNo: 'COL-1M',
    manufacturer: 'Cipla Critical Care',
    quantity: 180,
    unitOriginalPrice: 780,
    concessionPercent: 20,
    hospitalId: 'hosp-1',
    hospitalName: 'Apollo Hospital',
    location: 'Mumbai, Maharashtra',
    distanceKm: 0,
    dateAdded: '2024-08-25',
    notes: 'Reserve polymyxin antibiotic for carbapenem-resistant Pseudomonas.',
  },
  {
    id: 'med-125',
    brandName: 'Entecavir 0.5mg (Baraclude)',
    genericName: 'Entecavir Tablets USP 0.5mg',
    power: '0.5mg Film-Coated Tablets (Strip of 10)',
    category: 'Hepatology / Antiviral',
    storageType: 'Room Temperature (15°C - 30°C)',
    mfgDate: '2024-03-20',
    expiryDate: '2026-03-20',
    batchNo: 'ETV-500',
    manufacturer: 'Bristol-Myers Squibb / Zydus',
    quantity: 130,
    unitOriginalPrice: 1650,
    concessionPercent: 15,
    hospitalId: 'hosp-9',
    hospitalName: 'Kokilaben Dhirubhai Ambani Hospital',
    location: 'Mumbai, Maharashtra',
    distanceKm: 6.2,
    dateAdded: '2024-08-27',
    notes: 'Chronic hepatitis B viral replication suppression.',
  },
  {
    id: 'med-126',
    brandName: 'Midazolam Injection 5mg/ml (Mezolam)',
    genericName: 'Midazolam Hydrochloride Injection IP',
    power: '2ml Ampoule (Box of 10)',
    category: 'Anesthesia / Sedative',
    storageType: 'Protect from Light (<25°C)',
    mfgDate: '2024-02-14',
    expiryDate: '2025-08-14',
    batchNo: 'MDZ-05',
    manufacturer: 'Neon Laboratories',
    quantity: 260,
    unitOriginalPrice: 220,
    concessionPercent: 25,
    hospitalId: 'hosp-1',
    hospitalName: 'Apollo Hospital',
    location: 'Mumbai, Maharashtra',
    distanceKm: 0,
    dateAdded: '2024-08-26',
    notes: 'ICU ventilation and procedural sedation Schedule H1 drug.',
  },
  {
    id: 'med-127',
    brandName: 'Streptokinase 1,500,000 IU (STPase)',
    genericName: 'Streptokinase for Injection IP',
    power: '1.5 Million IU Lyophilized Vial',
    category: 'Cardiology / Thrombolytic',
    storageType: 'Room Temperature (2°C - 25°C)',
    mfgDate: '2023-10-01',
    expiryDate: new Date(Date.now() + 28 * 86400000).toISOString().split('T')[0], // 28 days left!
    batchNo: 'STK-150',
    manufacturer: 'Cadila Pharmaceuticals',
    quantity: 35,
    unitOriginalPrice: 2400,
    concessionPercent: 50,
    hospitalId: 'hosp-5',
    hospitalName: 'Lilavati Hospital & Research Centre',
    location: 'Mumbai, Maharashtra',
    distanceKm: 8.5,
    dateAdded: '2024-08-28',
    notes: 'URGENT: Acute myocardial infarction thrombolysis. Heavy 50% concession.',
  },
  {
    id: 'med-128',
    brandName: 'Dopamine Hydrochloride 200mg',
    genericName: 'Dopamine Hydrochloride Injection IP 40mg/ml',
    power: '5ml Ampoule (Box of 5)',
    category: 'Emergency / Vasopressor',
    storageType: 'Room Temperature (<30°C)',
    mfgDate: '2024-05-15',
    expiryDate: '2026-05-15',
    batchNo: 'DPM-200',
    manufacturer: 'VHB Life Sciences',
    quantity: 300,
    unitOriginalPrice: 175,
    concessionPercent: 15,
    hospitalId: 'hosp-7',
    hospitalName: 'Tata Memorial Centre',
    location: 'Mumbai, Maharashtra',
    distanceKm: 12.0,
    dateAdded: '2024-08-28',
    notes: 'Cardiogenic shock and hemodynamic resuscitation in ICU.',
  },
  {
    id: 'med-129',
    brandName: 'Bortezomib 3.5mg (Velcade)',
    genericName: 'Bortezomib for Injection IP',
    power: '3.5mg Single-Use Vial',
    category: 'Oncology / Proteasome Inhibitor',
    storageType: 'Protect from Light (2°C - 8°C)',
    mfgDate: '2024-01-30',
    expiryDate: '2025-07-30',
    batchNo: 'BTZ-35',
    manufacturer: 'Johnson & Johnson India',
    quantity: 18,
    unitOriginalPrice: 38500,
    concessionPercent: 28,
    hospitalId: 'hosp-7',
    hospitalName: 'Tata Memorial Centre',
    location: 'Mumbai, Maharashtra',
    distanceKm: 12.0,
    dateAdded: '2024-08-27',
    notes: 'Primary line therapy for multiple myeloma and mantle cell lymphoma.',
  },
  {
    id: 'med-130',
    brandName: 'Tranexamic Acid 500mg (Pause)',
    genericName: 'Tranexamic Acid Injection IP 100mg/ml',
    power: '5ml Ampoule (Box of 5)',
    category: 'Trauma / Hemostatic',
    storageType: 'Room Temperature (<25°C)',
    mfgDate: '2024-04-10',
    expiryDate: '2026-04-10',
    batchNo: 'TXA-500',
    manufacturer: 'Emcure Pharmaceuticals',
    quantity: 550,
    unitOriginalPrice: 125,
    concessionPercent: 12,
    hospitalId: 'hosp-1',
    hospitalName: 'Apollo Hospital',
    location: 'Mumbai, Maharashtra',
    distanceKm: 0,
    dateAdded: '2024-08-28',
    notes: 'Major trauma and cardiac surgery antifibrinolytic agent.',
  },

  // =========================================================================
  // DEMO DATA: COMPOSITION-BASED ALTERNATIVE MEDICINE GROUPS & NEGATIVE TESTS
  // =========================================================================

  // Group 1: Paracetamol 500mg Tablet (Oral) - Primary Dolo 500 & Composition Alternatives
  {
    id: 'med-dolo-500',
    brandName: 'Dolo 500',
    genericName: 'Paracetamol Tablets IP',
    power: '500 mg',
    category: 'Analgesics / Antipyretic',
    dosageForm: 'Tablet',
    route: 'Oral',
    activeIngredients: [{ name: 'Paracetamol', strength: 500, unit: 'mg' }],
    packSize: '15 tablets / strip',
    storageType: 'Room Temperature (<25°C)',
    mfgDate: '2024-04-12',
    expiryDate: '2027-04-30',
    batchNo: 'PCM2401',
    manufacturer: 'Micro Labs Ltd.',
    quantity: 1240,
    unitOriginalPrice: 1.50,
    concessionPercent: 20,
    hospitalId: 'hosp-city-1',
    hospitalName: 'City Hospital',
    location: 'Pune, Maharashtra',
    distanceKm: 8.5,
    verified: true,
    dateAdded: '2024-08-20',
    notes: 'Standard certified inpatient lot of Dolo 500 antipyretic tablets.',
    image: '/medicines/dolo_500_front.svg',
    images: [
      { label: 'Front', url: '/medicines/dolo_500_front.svg', alt: 'Dolo 500 medicine package front' },
      { label: 'Back', url: '/medicines/dolo_500_back.svg', alt: 'Dolo 500 blister foil reverse' },
      { label: 'Strip', url: '/medicines/dolo_500_strip.svg', alt: 'Dolo 500 blister strip' },
      { label: 'Package', url: '/medicines/dolo_500_box.svg', alt: 'Dolo 500 carton box' },
    ],
    invoice: {
      invoiceNumber: 'DEMO-INV-2401',
      invoiceDate: '12 Apr 2026',
      supplier: 'Sun Pharmaceutical Industries Ltd.',
      supplierAddress: 'Plot 22, MIDC Industrial Area, Pune, Maharashtra 411018',
      supplierDlNo: 'MH-PUN-20B-118492 / 21B-118493',
      supplierGstin: '27AABCM1234F1Z5',
      buyerHospital: 'City Hospital (Central Pharmacy Stores)',
      buyerAddress: '14 Senapati Bapat Road, Shivaji Nagar, Pune, Maharashtra 411016',
      buyerDlNo: 'MH-PUN-20B-998124',
      medicineName: 'Dolo 500',
      composition: 'Paracetamol 500 mg',
      dosageForm: 'Tablet',
      hsnCode: '30049099',
      batchNumber: 'PCM2401',
      mfgDate: '04/2024',
      expiryDate: '04/2027',
      quantity: 1000,
      rate: 1.20,
      amount: 1200.00,
      taxableAmount: 1200.00,
      cgstPercent: 6,
      cgstAmount: 72.00,
      sgstPercent: 6,
      sgstAmount: 72.00,
      totalTax: 144.00,
      total: 1344.00,
      paymentTerms: 'Net 30 Days Inter-Hospital Escrow',
      signatory: 'Authorized Pharmacist (Wholesale Supply)',
    },
  },
  {
    id: 'med-calpol-500',
    brandName: 'Calpol 500',
    genericName: 'Paracetamol Tablets IP 500mg',
    power: '500 mg',
    category: 'Analgesics / Antipyretic',
    dosageForm: 'Tablet',
    route: 'Oral',
    activeIngredients: [{ name: 'Paracetamol', strength: 500, unit: 'mg' }],
    packSize: '15 tablets / strip',
    storageType: 'Room Temperature (<25°C)',
    mfgDate: '2024-05-10',
    expiryDate: '2026-12-15',
    batchNo: 'CLP5-901',
    manufacturer: 'GlaxoSmithKline Pharmaceuticals',
    quantity: 820,
    unitOriginalPrice: 1.60,
    concessionPercent: 15.625,
    hospitalId: 'hosp-metro-1',
    hospitalName: 'Metro Hospital',
    location: 'Mumbai, Maharashtra',
    distanceKm: 15.0,
    verified: true,
    dateAdded: '2024-08-21',
    notes: 'Authorized hospital pharmacy surplus stock of Calpol 500.',
    image: '/medicines/calpol_500_front.svg',
    images: [
      { label: 'Front', url: '/medicines/calpol_500_front.svg', alt: 'Calpol 500 front blister strip' },
      { label: 'Package', url: '/medicines/dolo_500_box.svg', alt: 'Calpol 500 outer carton packaging' },
    ],
    invoice: {
      invoiceNumber: 'DEMO-INV-GSK-552',
      invoiceDate: '10 May 2026',
      supplier: 'GlaxoSmithKline Pharmaceuticals Ltd.',
      supplierAddress: 'Dr. Annie Besant Road, Worli, Mumbai 400030',
      supplierDlNo: 'MH-MUM-20B-441209',
      supplierGstin: '27AAACG0081C1ZN',
      buyerHospital: 'Metro Hospital (Inpatient Dispensary)',
      buyerAddress: '92 Bandra West, Mumbai, Maharashtra 400050',
      medicineName: 'Calpol 500',
      composition: 'Paracetamol 500 mg',
      dosageForm: 'Tablet',
      hsnCode: '30049099',
      batchNumber: 'CLP5-901',
      mfgDate: '05/2024',
      expiryDate: '12/2026',
      quantity: 800,
      rate: 1.35,
      amount: 1080.00,
      taxableAmount: 1080.00,
      cgstPercent: 6,
      cgstAmount: 64.80,
      sgstPercent: 6,
      sgstAmount: 64.80,
      totalTax: 129.60,
      total: 1209.60,
      paymentTerms: 'CDSCO Rule 65 Peer Transfer',
      signatory: 'GSK Depo Logistics Lead',
    },
  },
  {
    id: 'med-p-500',
    brandName: 'P-500',
    genericName: 'Paracetamol Tablets IP',
    power: '500 mg',
    category: 'Analgesics / Antipyretic',
    dosageForm: 'Tablet',
    route: 'Oral',
    activeIngredients: [{ name: 'Paracetamol', strength: 500, unit: 'mg' }],
    packSize: '10 tablets / strip',
    storageType: 'Room Temperature (<25°C)',
    mfgDate: '2024-03-15',
    expiryDate: '2027-01-20',
    batchNo: 'APX-551',
    manufacturer: 'Apex Laboratories Pvt Ltd',
    quantity: 640,
    unitOriginalPrice: 1.30,
    concessionPercent: 15.385,
    hospitalId: 'hosp-dist-1',
    hospitalName: 'District Hospital',
    location: 'Thane, Maharashtra',
    distanceKm: 24.0,
    verified: true,
    dateAdded: '2024-08-22',
    notes: 'Direct district hospital formulary stock of P-500 tablets.',
    image: '/medicines/p500_front.svg',
    images: [
      { label: 'Front', url: '/medicines/p500_front.svg', alt: 'P-500 front blister strip' },
    ],
    invoice: {
      invoiceNumber: 'DEMO-INV-APX-714',
      invoiceDate: '15 Mar 2026',
      supplier: 'Apex Laboratories Pvt Ltd',
      supplierAddress: 'MIDC Phase II, Dombivli, Thane 421204',
      supplierDlNo: 'MH-THA-20B-883190',
      supplierGstin: '27AABCA3319K1ZM',
      buyerHospital: 'District Hospital Thane',
      buyerAddress: 'Civil Hospital Road, Thane West 400601',
      medicineName: 'P-500',
      composition: 'Paracetamol 500 mg',
      dosageForm: 'Tablet',
      hsnCode: '30049099',
      batchNumber: 'APX-551',
      mfgDate: '03/2024',
      expiryDate: '01/2027',
      quantity: 600,
      rate: 1.10,
      amount: 660.00,
      taxableAmount: 660.00,
      cgstPercent: 6,
      cgstAmount: 39.60,
      sgstPercent: 6,
      sgstAmount: 39.60,
      totalTax: 79.20,
      total: 739.20,
      paymentTerms: 'District Health Service Escrow',
      signatory: 'Chief Pharmacist (Civil Supply)',
    },
  },
  {
    id: 'med-alt-pcm-2',
    brandName: 'ParaCare 500',
    genericName: 'Acetaminophen / Paracetamol IP',
    power: '500 mg',
    category: 'Analgesics / Antipyretic',
    dosageForm: 'Tablet',
    route: 'Oral',
    activeIngredients: [{ name: 'Paracetamol', strength: 500, unit: 'mg' }],
    packSize: '10 tablets / strip',
    storageType: 'Room Temperature (<25°C)',
    mfgDate: '2024-03-10',
    expiryDate: '2027-08-15',
    batchNo: 'PCR-502',
    manufacturer: 'Sun Pharma Industries',
    quantity: 320,
    unitOriginalPrice: 1.50,
    concessionPercent: 16.667,
    hospitalId: 'hosp-3',
    hospitalName: 'Max Super Speciality Hospital',
    location: 'New Delhi, Delhi',
    distanceKm: 22.0,
    verified: true,
    dateAdded: '2024-08-22',
    notes: 'Surplus inpatient antipyretic tablets available for immediate exchange.',
    image: '/medicines/paracare_front.svg',
    images: [
      { label: 'Front', url: '/medicines/paracare_front.svg', alt: 'ParaCare 500 front blister strip' },
    ],
    invoice: {
      invoiceNumber: 'DEMO-INV-SUN-992',
      invoiceDate: '10 Mar 2026',
      supplier: 'Sun Pharmaceutical Industries Ltd.',
      supplierAddress: 'Sun House, Western Express Highway, Goregaon East, Mumbai 400063',
      supplierDlNo: 'MH-MUM-20B-119283',
      supplierGstin: '27AAACS1120M1ZT',
      buyerHospital: 'Max Super Speciality Hospital',
      buyerAddress: '1 Press Enclave Marg, Saket, New Delhi 110017',
      medicineName: 'ParaCare 500',
      composition: 'Paracetamol 500 mg',
      dosageForm: 'Tablet',
      hsnCode: '30049099',
      batchNumber: 'PCR-502',
      mfgDate: '03/2024',
      expiryDate: '08/2027',
      quantity: 500,
      rate: 1.25,
      amount: 625.00,
      taxableAmount: 625.00,
      cgstPercent: 6,
      cgstAmount: 37.50,
      sgstPercent: 6,
      sgstAmount: 37.50,
      totalTax: 75.00,
      total: 700.00,
      paymentTerms: 'Form 20B Verified Batch Transfer',
      signatory: 'Regional Distribution Officer',
    },
  },
  {
    id: 'med-alt-pcm-3',
    brandName: 'FeverSafe 500',
    genericName: 'Paracetamol IP 500mg',
    power: '500mg Tablets (Strip of 10)',
    category: 'Analgesics / Antipyretic',
    dosageForm: 'Tablet',
    route: 'Oral',
    activeIngredients: [{ name: 'Paracetamol', strength: 500, unit: 'mg' }],
    storageType: 'Room Temperature (<25°C)',
    mfgDate: '2024-06-15',
    expiryDate: '2027-02-10',
    batchNo: 'FVS-2499',
    manufacturer: 'Torrent Pharmaceuticals',
    quantity: 600,
    unitOriginalPrice: 28,
    concessionPercent: 30,
    hospitalId: 'hosp-7',
    hospitalName: 'Tata Memorial Centre',
    location: 'Mumbai, Maharashtra',
    distanceKm: 12.0,
    dateAdded: '2024-08-24',
    notes: 'Standard therapeutic composition lot with long shelf-life.',
  },
  {
    id: 'med-alt-pcm-4',
    brandName: 'Crocin 500 Advance',
    genericName: 'Paracetamol Fast Release IP',
    power: '500mg Tablets (Strip of 15)',
    category: 'Analgesics / Antipyretic',
    dosageForm: 'Tablet',
    route: 'Oral',
    activeIngredients: [{ name: 'Paracetamol', strength: 500, unit: 'mg' }],
    storageType: 'Room Temperature (<25°C)',
    mfgDate: '2024-04-20',
    expiryDate: '2026-09-30',
    batchNo: 'CRC-8812',
    manufacturer: 'GlaxoSmithKline Consumer',
    quantity: 280,
    unitOriginalPrice: 42,
    concessionPercent: 15,
    hospitalId: 'hosp-8',
    hospitalName: 'All India Institute of Medical Sciences (AIIMS)',
    location: 'New Delhi, Delhi',
    distanceKm: 0,
    dateAdded: '2024-08-25',
    notes: 'Trusted branded Paracetamol 500mg release formulation.',
  },

  // Group 2: Amoxicillin 500mg Capsule (Oral)
  {
    id: 'med-alt-amx-1',
    brandName: 'AmoxiCare 500',
    genericName: 'Amoxicillin Capsules IP',
    power: '500mg Capsules (Strip of 10)',
    category: 'Antibiotics / Penicillin',
    dosageForm: 'Capsule',
    route: 'Oral',
    activeIngredients: [{ name: 'Amoxicillin', strength: 500, unit: 'mg' }],
    storageType: 'Dry & Cool (<25°C)',
    mfgDate: '2024-04-10',
    expiryDate: '2026-10-12',
    batchNo: 'AMX-500-C1',
    manufacturer: 'Alkem Laboratories',
    quantity: 180,
    unitOriginalPrice: 75,
    concessionPercent: 20,
    hospitalId: 'hosp-2',
    hospitalName: 'Fortis Memorial Research Institute',
    location: 'Gurgaon, Haryana',
    distanceKm: 14.5,
    dateAdded: '2024-08-21',
    notes: 'Pure Amoxicillin 500mg single-agent antibiotic capsules.',
  },
  {
    id: 'med-alt-amx-2',
    brandName: 'MediAmox 500',
    genericName: 'Amoxicillin Trihydrate IP',
    power: '500mg Capsules (Strip of 10)',
    category: 'Antibiotics / Penicillin',
    dosageForm: 'Capsule',
    route: 'Oral',
    activeIngredients: [{ name: 'Amoxicillin', strength: 500, unit: 'mg' }],
    storageType: 'Dry & Cool (<25°C)',
    mfgDate: '2024-05-15',
    expiryDate: '2026-12-05',
    batchNo: 'MAM-500-L2',
    manufacturer: 'Lupin Pharmaceuticals',
    quantity: 240,
    unitOriginalPrice: 70,
    concessionPercent: 22,
    hospitalId: 'hosp-3',
    hospitalName: 'Max Super Speciality Hospital',
    location: 'New Delhi, Delhi',
    distanceKm: 22.0,
    dateAdded: '2024-08-23',
    notes: 'Equivalent broad-spectrum penicillin monotherapy capsules.',
  },
  {
    id: 'med-alt-amx-3',
    brandName: 'AmoxiPlus 500',
    genericName: 'Amoxicillin Capsules BP',
    power: '500mg Capsules (Strip of 10)',
    category: 'Antibiotics / Penicillin',
    dosageForm: 'Capsule',
    route: 'Oral',
    activeIngredients: [{ name: 'Amoxicillin', strength: 500, unit: 'mg' }],
    storageType: 'Dry & Cool (<25°C)',
    mfgDate: '2024-06-01',
    expiryDate: '2027-01-20',
    batchNo: 'APL-500-Z3',
    manufacturer: 'Zydus Lifesciences',
    quantity: 310,
    unitOriginalPrice: 72,
    concessionPercent: 25,
    hospitalId: 'hosp-9',
    hospitalName: 'Kokilaben Dhirubhai Ambani Hospital',
    location: 'Mumbai, Maharashtra',
    distanceKm: 6.2,
    dateAdded: '2024-08-25',
    notes: 'Direct composition match for Amoxicillin 500mg oral capsules.',
  },

  // Group 3: Cetirizine 10mg Tablet (Oral)
  {
    id: 'med-alt-cet-1',
    brandName: 'CetiClear 10',
    genericName: 'Cetirizine Hydrochloride IP',
    power: '10mg Tablets (Strip of 10)',
    category: 'Allergy / Antihistamine',
    dosageForm: 'Tablet',
    route: 'Oral',
    activeIngredients: [{ name: 'Cetirizine', strength: 10, unit: 'mg' }],
    storageType: 'Room Temperature (15°C - 30°C)',
    mfgDate: '2024-05-10',
    expiryDate: '2027-03-15',
    batchNo: 'CTC-10A',
    manufacturer: "Dr. Reddy's Laboratories",
    quantity: 500,
    unitOriginalPrice: 38,
    concessionPercent: 20,
    hospitalId: 'hosp-3',
    hospitalName: 'Max Super Speciality Hospital',
    location: 'New Delhi, Delhi',
    distanceKm: 22.0,
    dateAdded: '2024-08-22',
    notes: 'Non-sedating antihistamine 10mg tablets for allergic rhinitis.',
  },
  {
    id: 'med-alt-cet-2',
    brandName: 'AllerFree 10',
    genericName: 'Cetirizine Dihydrochloride IP',
    power: '10mg Tablets (Strip of 10)',
    category: 'Allergy / Antihistamine',
    dosageForm: 'Tablet',
    route: 'Oral',
    activeIngredients: [{ name: 'Cetirizine', strength: 10, unit: 'mg' }],
    storageType: 'Room Temperature (15°C - 30°C)',
    mfgDate: '2024-04-05',
    expiryDate: '2026-11-10',
    batchNo: 'ALF-10B',
    manufacturer: 'Cipla Healthcare',
    quantity: 420,
    unitOriginalPrice: 40,
    concessionPercent: 25,
    hospitalId: 'hosp-7',
    hospitalName: 'Tata Memorial Centre',
    location: 'Mumbai, Maharashtra',
    distanceKm: 12.0,
    dateAdded: '2024-08-24',
    notes: 'Identical 10mg Cetirizine oral formulation.',
  },
  {
    id: 'med-alt-cet-3',
    brandName: 'CetiCare 10',
    genericName: 'Cetirizine Tablets IP',
    power: '10mg Tablets (Strip of 10)',
    category: 'Allergy / Antihistamine',
    dosageForm: 'Tablet',
    route: 'Oral',
    activeIngredients: [{ name: 'Cetirizine', strength: 10, unit: 'mg' }],
    storageType: 'Room Temperature (15°C - 30°C)',
    mfgDate: '2024-06-18',
    expiryDate: '2027-04-18',
    batchNo: 'CKR-10C',
    manufacturer: 'Mankind Pharma',
    quantity: 380,
    unitOriginalPrice: 35,
    concessionPercent: 20,
    hospitalId: 'hosp-8',
    hospitalName: 'All India Institute of Medical Sciences (AIIMS)',
    location: 'New Delhi, Delhi',
    distanceKm: 0,
    dateAdded: '2024-08-26',
    notes: 'Affordable bioequivalent alternative for 10mg Cetirizine.',
  },

  // Group 4: Pantoprazole 40mg Tablet (Oral)
  {
    id: 'med-alt-pan-1',
    brandName: 'PantoCare 40',
    genericName: 'Pantoprazole Gastro-Resistant Tablets IP',
    power: '40mg Enteric-Coated Tablets',
    category: 'Gastroenterology / PPI',
    dosageForm: 'Tablet',
    route: 'Oral',
    activeIngredients: [{ name: 'Pantoprazole', strength: 40, unit: 'mg' }],
    storageType: 'Protect from Moisture (<25°C)',
    mfgDate: '2024-03-12',
    expiryDate: '2026-09-22',
    batchNo: 'PTC-40A',
    manufacturer: 'Alkem Laboratories',
    quantity: 350,
    unitOriginalPrice: 95,
    concessionPercent: 25,
    hospitalId: 'hosp-2',
    hospitalName: 'Fortis Memorial Research Institute',
    location: 'Gurgaon, Haryana',
    distanceKm: 14.5,
    dateAdded: '2024-08-20',
    notes: 'Proton-pump inhibitor 40mg enteric-coated tablets for acid peptic disease.',
  },
  {
    id: 'med-alt-pan-2',
    brandName: 'AcidSafe 40',
    genericName: 'Pantoprazole Sodium IP 40mg',
    power: '40mg Tablets (Strip of 15)',
    category: 'Gastroenterology / PPI',
    dosageForm: 'Tablet',
    route: 'Oral',
    activeIngredients: [{ name: 'Pantoprazole', strength: 40, unit: 'mg' }],
    storageType: 'Protect from Moisture (<25°C)',
    mfgDate: '2024-05-18',
    expiryDate: '2027-01-14',
    batchNo: 'ASF-40B',
    manufacturer: 'Torrent Pharmaceuticals',
    quantity: 290,
    unitOriginalPrice: 90,
    concessionPercent: 20,
    hospitalId: 'hosp-3',
    hospitalName: 'Max Super Speciality Hospital',
    location: 'New Delhi, Delhi',
    distanceKm: 22.0,
    dateAdded: '2024-08-23',
    notes: 'Identical acid suppression active strength with high bioavailability.',
  },
  {
    id: 'med-alt-pan-3',
    brandName: 'PantoRelief 40',
    genericName: 'Pantoprazole Delayed-Release Tablets USP',
    power: '40mg Tablets (Strip of 10)',
    category: 'Gastroenterology / PPI',
    dosageForm: 'Tablet',
    route: 'Oral',
    activeIngredients: [{ name: 'Pantoprazole', strength: 40, unit: 'mg' }],
    storageType: 'Protect from Moisture (<25°C)',
    mfgDate: '2024-06-05',
    expiryDate: '2026-12-30',
    batchNo: 'PTR-40C',
    manufacturer: 'Sun Pharma Industries',
    quantity: 410,
    unitOriginalPrice: 92,
    concessionPercent: 22,
    hospitalId: 'hosp-9',
    hospitalName: 'Kokilaben Dhirubhai Ambani Hospital',
    location: 'Mumbai, Maharashtra',
    distanceKm: 6.2,
    dateAdded: '2024-08-25',
    notes: 'Verified hospital lot of 40mg Pantoprazole tablets.',
  },

  // Group 5: Multi-Component (Amoxicillin 500mg + Clavulanic Acid 125mg Tablet Oral)
  {
    id: 'med-alt-aug-1',
    brandName: 'Augmentin 625 Duo',
    genericName: 'Amoxicillin and Potassium Clavulanate Tablets IP',
    power: '625mg (500mg + 125mg) Tablets',
    category: 'Antibiotics / Penicillin Combo',
    dosageForm: 'Tablet',
    route: 'Oral',
    activeIngredients: [
      { name: 'Amoxicillin', strength: 500, unit: 'mg' },
      { name: 'Clavulanic Acid', strength: 125, unit: 'mg' }
    ],
    storageType: 'Dry & Cool (<25°C)',
    mfgDate: '2024-04-15',
    expiryDate: '2026-10-30',
    batchNo: 'AUG-625-D1',
    manufacturer: 'GlaxoSmithKline Pharma',
    quantity: 140,
    unitOriginalPrice: 220,
    concessionPercent: 15,
    hospitalId: 'hosp-2',
    hospitalName: 'Fortis Memorial Research Institute',
    location: 'Gurgaon, Haryana',
    distanceKm: 14.5,
    dateAdded: '2024-08-21',
    notes: 'Gold-standard co-amoxiclav 625mg broad-spectrum antibiotic.',
  },
  {
    id: 'med-alt-aug-2',
    brandName: 'Clavam 625',
    genericName: 'Amoxicillin and Clavulanic Acid Tablets IP',
    power: '625mg (500mg + 125mg) Tablets',
    category: 'Antibiotics / Penicillin Combo',
    dosageForm: 'Tablet',
    route: 'Oral',
    activeIngredients: [
      { name: 'Amoxicillin', strength: 500, unit: 'mg' },
      { name: 'Clavulanic Acid', strength: 125, unit: 'mg' }
    ],
    storageType: 'Dry & Cool (<25°C)',
    mfgDate: '2024-05-20',
    expiryDate: '2026-11-15',
    batchNo: 'CLV-625-A2',
    manufacturer: 'Alkem Laboratories',
    quantity: 220,
    unitOriginalPrice: 205,
    concessionPercent: 18,
    hospitalId: 'hosp-3',
    hospitalName: 'Max Super Speciality Hospital',
    location: 'New Delhi, Delhi',
    distanceKm: 22.0,
    dateAdded: '2024-08-23',
    notes: 'Bioequivalent alternative formulation with identical active ratio.',
  },
  {
    id: 'med-alt-aug-3',
    brandName: 'Moxikind-CV 625',
    genericName: 'Potassium Clavulanate and Amoxicillin Tablets IP',
    power: '625mg (500mg + 125mg) Tablets',
    category: 'Antibiotics / Penicillin Combo',
    dosageForm: 'Tablet',
    route: 'Oral',
    activeIngredients: [
      { name: 'Amoxicillin', strength: 500, unit: 'mg' },
      { name: 'Clavulanic Acid', strength: 125, unit: 'mg' }
    ],
    storageType: 'Dry & Cool (<25°C)',
    mfgDate: '2024-06-10',
    expiryDate: '2027-02-28',
    batchNo: 'MXK-625-M3',
    manufacturer: 'Mankind Pharma',
    quantity: 300,
    unitOriginalPrice: 195,
    concessionPercent: 20,
    hospitalId: 'hosp-8',
    hospitalName: 'All India Institute of Medical Sciences (AIIMS)',
    location: 'New Delhi, Delhi',
    distanceKm: 0,
    dateAdded: '2024-08-26',
    notes: 'High-availability verified stock of 625mg Co-Amoxiclav.',
  },

  // =========================================================================
  // NEGATIVE TEST MEDICINES (Must NOT be matched as identical alternatives)
  // =========================================================================
  {
    id: 'med-neg-1',
    brandName: 'Dolo 650 Tablets',
    genericName: 'Paracetamol Tablets IP 650mg',
    power: '650mg Tablets (Strip of 15)',
    category: 'Analgesics / Antipyretic',
    dosageForm: 'Tablet',
    route: 'Oral',
    activeIngredients: [{ name: 'Paracetamol', strength: 650, unit: 'mg' }], // Different strength (650mg vs 500mg)
    storageType: 'Room Temperature (<25°C)',
    mfgDate: '2024-04-18',
    expiryDate: '2026-10-18',
    batchNo: 'DLO-650-M1',
    manufacturer: 'Micro Labs Limited',
    quantity: 400,
    unitOriginalPrice: 38,
    concessionPercent: 10,
    hospitalId: 'hosp-2',
    hospitalName: 'Fortis Memorial Research Institute',
    location: 'Gurgaon, Haryana',
    distanceKm: 14.5,
    dateAdded: '2024-08-20',
    notes: 'Negative Test: 650mg strength must never be presented as exact alternative to 500mg.',
  },
  {
    id: 'med-neg-2',
    brandName: 'Calpol Pediatric Suspension',
    genericName: 'Paracetamol Paediatric Oral Suspension',
    power: '250mg / 5ml Syrup (60ml Bottle)',
    category: 'Pediatric / Antipyretic',
    dosageForm: 'Syrup', // Different dosage form (Syrup vs Tablet)
    route: 'Oral',
    activeIngredients: [{ name: 'Paracetamol', strength: 250, unit: 'mg/5ml' }],
    storageType: 'Room Temperature (<25°C)',
    mfgDate: '2024-03-01',
    expiryDate: '2026-09-01',
    batchNo: 'CLP-250-S1',
    manufacturer: 'GlaxoSmithKline Healthcare',
    quantity: 90,
    unitOriginalPrice: 48,
    concessionPercent: 12,
    hospitalId: 'hosp-3',
    hospitalName: 'Max Super Speciality Hospital',
    location: 'New Delhi, Delhi',
    distanceKm: 22.0,
    dateAdded: '2024-08-22',
    notes: 'Negative Test: Oral syrup formulation must never match solid oral tablet.',
  },
  {
    id: 'med-neg-3',
    brandName: 'Paracetamol Sterile IV Infusion',
    genericName: 'Paracetamol Intravenous Infusion 10mg/ml',
    power: '1000mg / 100ml Infusion Bottle',
    category: 'Critical Care / Analgesic',
    dosageForm: 'Infusion', // Different form & route (IV Infusion vs Oral Tablet)
    route: 'Intravenous',
    activeIngredients: [{ name: 'Paracetamol', strength: 1000, unit: 'mg' }],
    storageType: 'Room Temperature (<30°C)',
    mfgDate: '2024-02-15',
    expiryDate: '2026-08-15',
    batchNo: 'PCM-IV-100',
    manufacturer: 'Intas Pharmaceuticals',
    quantity: 120,
    unitOriginalPrice: 65,
    concessionPercent: 30,
    hospitalId: 'hosp-7',
    hospitalName: 'Tata Memorial Centre',
    location: 'Mumbai, Maharashtra',
    distanceKm: 12.0,
    dateAdded: '2024-08-24',
    notes: 'Negative Test: Intravenous infusion route must never match oral tablets.',
  },
  {
    id: 'med-neg-4',
    brandName: 'Amoxil 250 Capsules',
    genericName: 'Amoxicillin Capsules BP 250mg',
    power: '250mg Capsules (Strip of 10)',
    category: 'Antibiotics / Penicillin',
    dosageForm: 'Capsule',
    route: 'Oral',
    activeIngredients: [{ name: 'Amoxicillin', strength: 250, unit: 'mg' }], // Different strength (250mg vs 500mg)
    storageType: 'Dry & Cool (<25°C)',
    mfgDate: '2024-05-05',
    expiryDate: '2026-11-05',
    batchNo: 'AMX-250-G1',
    manufacturer: 'GlaxoSmithKline Pharma',
    quantity: 150,
    unitOriginalPrice: 45,
    concessionPercent: 15,
    hospitalId: 'hosp-2',
    hospitalName: 'Fortis Memorial Research Institute',
    location: 'Gurgaon, Haryana',
    distanceKm: 14.5,
    dateAdded: '2024-08-21',
    notes: 'Negative Test: 250mg strength must never match 500mg capsule requests.',
  },
  {
    id: 'med-neg-5',
    brandName: 'Novamox 500 Capsules',
    genericName: 'Amoxicillin Capsules IP 500mg',
    power: '500mg Capsules',
    category: 'Antibiotics / Penicillin',
    dosageForm: 'Capsule',
    route: 'Oral',
    activeIngredients: [{ name: 'Amoxicillin', strength: 500, unit: 'mg' }], // Missing Clavulanic Acid component!
    storageType: 'Dry & Cool (<25°C)',
    mfgDate: '2024-06-12',
    expiryDate: '2026-12-12',
    batchNo: 'NVM-500-C1',
    manufacturer: 'Cipla Healthcare',
    quantity: 220,
    unitOriginalPrice: 74,
    concessionPercent: 18,
    hospitalId: 'hosp-3',
    hospitalName: 'Max Super Speciality Hospital',
    location: 'New Delhi, Delhi',
    distanceKm: 22.0,
    dateAdded: '2024-08-23',
    notes: 'Negative Test: Monotherapy Amoxicillin must not match dual-agent Amoxicillin + Clavulanate.',
  }
];

export const INITIAL_REQUESTS = [
  // Competing Requisition Pair for First-Acceptance-Wins Demo
  {
    id: 'req-competing-1',
    requirementGroupId: 'req-group-meropenem-101',
    medicineId: 'med-101',
    medicineName: 'Meropenem Injection 1g IV Vial',
    power: '1g IV Vial',
    quantity: 25,
    unitOriginalPrice: 1850,
    concessionPercent: 35,
    unitFinalPrice: 1202.5,
    totalAmount: 30062.5,
    fromHospitalId: 'hosp-1',
    fromHospitalName: 'Apollo Hospital',
    toHospitalId: 'hosp-2',
    toHospitalName: 'Fortis Memorial Research Institute',
    requestDate: new Date(Date.now() - 3 * 3600 * 1000).toISOString(), // 3 hours ago
    expiryDate: new Date(Date.now() + 45 * 3600 * 1000).toISOString(), // 45 hours left
    status: 'pending',
    rejectReason: null,
    transactionId: 'TXN-984210',
    paymentId: null,
    paymentStatus: 'pending',
    notes: 'Urgent ICU requirement (Dual Requisition - First seller acceptance locks allocation).',
  },
  {
    id: 'req-competing-2',
    requirementGroupId: 'req-group-meropenem-101',
    medicineId: 'med-101',
    medicineName: 'Meropenem Injection 1g IV Vial',
    power: '1g IV Vial',
    quantity: 25,
    unitOriginalPrice: 1850,
    concessionPercent: 35,
    unitFinalPrice: 1202.5,
    totalAmount: 30062.5,
    fromHospitalId: 'hosp-1',
    fromHospitalName: 'Apollo Hospital',
    toHospitalId: 'hosp-3',
    toHospitalName: 'Max Super Speciality Hospital',
    requestDate: new Date(Date.now() - 3 * 3600 * 1000).toISOString(), // 3 hours ago
    expiryDate: new Date(Date.now() + 45 * 3600 * 1000).toISOString(), // 45 hours left
    status: 'pending',
    rejectReason: null,
    transactionId: 'TXN-984211',
    paymentId: null,
    paymentStatus: 'pending',
    notes: 'Urgent ICU requirement (Dual Requisition - Competing peer request).',
  },
  // Paid & In Transit Request
  {
    id: 'req-202',
    requirementGroupId: null,
    medicineId: 'med-102',
    medicineName: 'Enoxaparin Sodium 40mg Prefilled Syringe',
    power: '40mg / 0.4ml',
    quantity: 50,
    unitOriginalPrice: 480,
    concessionPercent: 25,
    unitFinalPrice: 360,
    totalAmount: 18000,
    fromHospitalId: 'hosp-1',
    fromHospitalName: 'Apollo Hospital',
    toHospitalId: 'hosp-3',
    toHospitalName: 'Max Super Speciality Hospital',
    requestDate: '2024-08-25T14:15:00Z',
    expiryDate: '2024-08-27T14:15:00Z',
    status: 'paid',
    rejectReason: null,
    transactionId: 'TXN-773120',
    paymentId: 'pay_Nz8849qK91Xza',
    paymentStatus: 'success',
    paidDate: '2024-08-26T09:45:00Z',
    notes: 'Post-op cardiac recovery unit allocation.',
  },
  // Expired Requisition (48-Hour SLA Expired)
  {
    id: 'req-203-exp',
    requirementGroupId: null,
    medicineId: 'med-103',
    medicineName: 'Human Albumin 20% 100ml Infusion Bottle',
    power: '100ml Infusion Bottle',
    quantity: 10,
    unitOriginalPrice: 4200,
    concessionPercent: 20,
    unitFinalPrice: 3360,
    totalAmount: 33600,
    fromHospitalId: 'hosp-1',
    fromHospitalName: 'Apollo Hospital',
    toHospitalId: 'hosp-2',
    toHospitalName: 'Fortis Memorial Research Institute',
    requestDate: new Date(Date.now() - 72 * 3600 * 1000).toISOString(), // 72 hours ago
    expiryDate: new Date(Date.now() - 24 * 3600 * 1000).toISOString(), // expired 24h ago
    status: 'expired',
    rejectReason: 'Automated 48-Hour SLA Expiration: Seller did not confirm within 48 hours.',
    transactionId: 'TXN-551982',
    paymentId: null,
    paymentStatus: 'pending',
    notes: 'Emergency liver transplant support reservation.',
  },
  // Rejected Requisition
  {
    id: 'req-204',
    requirementGroupId: null,
    medicineId: 'med-109',
    medicineName: 'Trastuzumab (Herclon) 440mg',
    power: '440mg Multi-dose Vial',
    quantity: 4,
    unitOriginalPrice: 54000,
    concessionPercent: 20,
    unitFinalPrice: 43200,
    totalAmount: 172800,
    fromHospitalId: 'hosp-1',
    fromHospitalName: 'Apollo Hospital',
    toHospitalId: 'hosp-3',
    toHospitalName: 'Max Super Speciality Hospital',
    requestDate: '2024-08-20T08:30:00Z',
    expiryDate: '2024-08-22T08:30:00Z',
    status: 'rejected',
    rejectReason: 'Requested batch reserved for scheduled chemotherapy sessions in oncology wing.',
    transactionId: 'TXN-331092',
    paymentId: null,
    paymentStatus: 'failed',
    notes: 'Oncology breast cancer protocol batch.',
  },
  // Incoming requests for Apollo (where toHospitalId is 'hosp-1')
  {
    id: 'req-205',
    requirementGroupId: null,
    medicineId: 'med-105',
    medicineName: 'Pantoprazole IV 40mg Vial',
    power: '40mg Vial',
    quantity: 100,
    unitOriginalPrice: 65,
    concessionPercent: 40,
    unitFinalPrice: 39,
    totalAmount: 3900,
    fromHospitalId: 'hosp-2',
    fromHospitalName: 'Fortis Memorial Research Institute',
    toHospitalId: 'hosp-1',
    toHospitalName: 'Apollo Hospital',
    requestDate: new Date(Date.now() - 4 * 3600 * 1000).toISOString(), // 4h ago
    expiryDate: new Date(Date.now() + 44 * 3600 * 1000).toISOString(),
    status: 'pending',
    rejectReason: null,
    transactionId: 'TXN-881920',
    paymentId: null,
    paymentStatus: 'pending',
    notes: 'Regular replenishment for emergency wards.',
  },
  {
    id: 'req-206',
    requirementGroupId: null,
    medicineId: 'med-106',
    medicineName: 'Insulin Glargine (Lantus) SoloStar',
    power: '3ml SoloStar Pen',
    quantity: 25,
    unitOriginalPrice: 890,
    concessionPercent: 30,
    unitFinalPrice: 623,
    totalAmount: 15575,
    fromHospitalId: 'hosp-3',
    fromHospitalName: 'Max Super Speciality Hospital',
    toHospitalId: 'hosp-1',
    toHospitalName: 'Apollo Hospital',
    requestDate: new Date(Date.now() - 6 * 3600 * 1000).toISOString(), // 6h ago
    expiryDate: new Date(Date.now() + 42 * 3600 * 1000).toISOString(),
    status: 'pending',
    rejectReason: null,
    transactionId: 'TXN-442819',
    paymentId: null,
    paymentStatus: 'pending',
    notes: 'Endocrinology diabetic patient inpatient supplies.',
  },
  {
    id: 'req-207',
    requirementGroupId: null,
    medicineId: 'med-113',
    medicineName: 'Propofol Injection 1% 20ml Vial',
    power: '20ml Single-Dose Vial',
    quantity: 40,
    unitOriginalPrice: 380,
    concessionPercent: 35,
    unitFinalPrice: 247,
    totalAmount: 9880,
    fromHospitalId: 'hosp-5',
    fromHospitalName: 'Lilavati Hospital & Research Centre',
    toHospitalId: 'hosp-1',
    toHospitalName: 'Apollo Hospital',
    requestDate: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    expiryDate: new Date(Date.now() + 43 * 3600 * 1000).toISOString(),
    status: 'accepted',
    rejectReason: null,
    transactionId: 'TXN-550912',
    paymentId: null,
    paymentStatus: 'pending',
    notes: 'Elective neurosurgery operative batch allocation.',
  },
  {
    id: 'req-208',
    requirementGroupId: null,
    medicineId: 'med-115',
    medicineName: 'Rituximab (Ristova) 500mg',
    power: '500mg / 50ml Vial',
    quantity: 4,
    unitOriginalPrice: 82000,
    concessionPercent: 25,
    unitFinalPrice: 61500,
    totalAmount: 246000,
    fromHospitalId: 'hosp-1',
    fromHospitalName: 'Apollo Hospital',
    toHospitalId: 'hosp-7',
    toHospitalName: 'Tata Memorial Centre',
    requestDate: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    expiryDate: new Date(Date.now() + 34 * 3600 * 1000).toISOString(),
    status: 'paid',
    rejectReason: null,
    transactionId: 'TXN-770412',
    paymentId: 'pay_Rtx99120aK8',
    paymentStatus: 'success',
    paidDate: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
    notes: 'Emergency oncology immunotherapy protocol.',
  },
  {
    id: 'req-209',
    requirementGroupId: null,
    medicineId: 'med-120',
    medicineName: 'Heparin Sodium 25,000 IU',
    power: '5ml Multi-Dose Vial',
    quantity: 60,
    unitOriginalPrice: 520,
    concessionPercent: 25,
    unitFinalPrice: 390,
    totalAmount: 23400,
    fromHospitalId: 'hosp-9',
    fromHospitalName: 'Kokilaben Dhirubhai Ambani Hospital',
    toHospitalId: 'hosp-1',
    toHospitalName: 'Apollo Hospital',
    requestDate: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
    expiryDate: new Date(Date.now() + 38 * 3600 * 1000).toISOString(),
    status: 'pending',
    rejectReason: null,
    transactionId: 'TXN-884019',
    paymentId: null,
    paymentStatus: 'pending',
    notes: 'Cardiothoracic bypass perfusion reservation.',
  },
  {
    id: 'req-210',
    requirementGroupId: null,
    medicineId: 'med-122',
    medicineName: 'Liposomal Amphotericin B 50mg',
    power: '50mg Lyophilized Cake',
    quantity: 15,
    unitOriginalPrice: 6200,
    concessionPercent: 25,
    unitFinalPrice: 4650,
    totalAmount: 69750,
    fromHospitalId: 'hosp-1',
    fromHospitalName: 'Apollo Hospital',
    toHospitalId: 'hosp-8',
    toHospitalName: 'All India Institute of Medical Sciences (AIIMS)',
    requestDate: new Date(Date.now() - 40 * 3600 * 1000).toISOString(), // 40h ago -> only 8h left!
    expiryDate: new Date(Date.now() + 8 * 3600 * 1000).toISOString(),
    status: 'pending',
    rejectReason: null,
    transactionId: 'TXN-910482',
    paymentId: null,
    paymentStatus: 'pending',
    notes: 'CRITICAL ICU: Severe fungal infection. Expiring in 8 hours!',
  },
  {
    id: 'req-211',
    requirementGroupId: null,
    medicineId: 'med-127',
    medicineName: 'Streptokinase 1,500,000 IU',
    power: '1.5 Million IU Vial',
    quantity: 12,
    unitOriginalPrice: 2400,
    concessionPercent: 50,
    unitFinalPrice: 1200,
    totalAmount: 14400,
    fromHospitalId: 'hosp-1',
    fromHospitalName: 'Apollo Hospital',
    toHospitalId: 'hosp-5',
    toHospitalName: 'Lilavati Hospital & Research Centre',
    requestDate: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
    expiryDate: new Date(Date.now() + 28 * 3600 * 1000).toISOString(),
    status: 'dispatched',
    rejectReason: null,
    transactionId: 'TXN-663190',
    paymentId: 'pay_Stk88190bM2',
    paymentStatus: 'success',
    paidDate: new Date(Date.now() - 16 * 3600 * 1000).toISOString(),
    notes: 'Emergency cardiac cath lab buffer transfer.',
  },
  {
    id: 'req-212',
    requirementGroupId: null,
    medicineId: 'med-118',
    medicineName: 'Bevacizumab (Avastin) 400mg',
    power: '400mg / 16ml Vial',
    quantity: 3,
    unitOriginalPrice: 65000,
    concessionPercent: 30,
    unitFinalPrice: 45500,
    totalAmount: 136500,
    fromHospitalId: 'hosp-2',
    fromHospitalName: 'Fortis Memorial Research Institute',
    toHospitalId: 'hosp-7',
    toHospitalName: 'Tata Memorial Centre',
    requestDate: '2024-08-24T10:00:00Z',
    expiryDate: '2024-08-26T10:00:00Z',
    status: 'delivered',
    rejectReason: null,
    transactionId: 'TXN-331902',
    paymentId: 'pay_Bvz44190xT1',
    paymentStatus: 'success',
    paidDate: '2024-08-24T12:30:00Z',
    notes: 'Completed delivery under certified 4.1°C cold chain.',
  }
];

export const INITIAL_TRACKING = [
  {
    transactionId: 'TXN-773120',
    trackingNumber: 'SMS-EXP-88912',
    senderHospital: 'Max Super Speciality Hospital (Delhi)',
    receiverHospital: 'Apollo Hospital (Mumbai)',
    medicineName: 'Enoxaparin Sodium 40mg',
    quantity: 50,
    status: 'In Transit',
    currentLocation: 'NH-48 Logistic Hub, Vadodara, Gujarat',
    destination: 'Apollo Hospital Central Pharmacy, Belapur, Mumbai',
    eta: 'Today, 06:30 PM (Est. 4 hrs)',
    courierName: 'MediCold Logistics Express Ltd.',
    courierContact: '+91 91234 56789 (Driver: Harpreet Singh)',
    vehicleNo: 'MH-04-AZ-4419 (Temp Controlled)',
    temperature: '4.2°C (Compliant)',
    timeline: [
      { step: 'Order Placed & Verified', date: '2024-08-25 14:15', completed: true, details: 'Verified by SmartMediShare verification engine.' },
      { step: 'Payment Processed via Razorpay', date: '2024-08-26 09:45', completed: true, details: 'Ref: pay_Nz8849qK91Xza, ₹18,000 settled.' },
      { step: 'Dispatched & Cold Seal Applied', date: '2024-08-26 15:30', completed: true, details: 'Dispatched from Saket Hub, Temp: 3.8°C.' },
      { step: 'In Transit with Live IoT GPS/Temp', date: '2024-08-27 11:20', completed: true, details: 'Crossing Vadodara Hub checkpoint.' },
      { step: 'Delivered to Receiving Hospital', date: 'Pending', completed: false, details: 'Target delivery at Mumbai pharmacy intake dock.' },
    ],
    coordinates: {
      origin: [28.5273, 77.2155], // Delhi
      current: [22.3072, 73.1812], // Vadodara
      destination: [19.0144, 73.0408], // Belapur Mumbai
    }
  },
  {
    transactionId: 'TXN-984210',
    trackingNumber: 'SMS-EXP-99210',
    senderHospital: 'Fortis Memorial Research Institute',
    receiverHospital: 'Apollo Hospital',
    medicineName: 'Meropenem Injection 1g IV',
    quantity: 20,
    status: 'Ordered',
    currentLocation: 'Fortis Gurgaon Warehouse Dispatch Dock',
    destination: 'Apollo Hospital Mumbai',
    eta: 'Tomorrow, 02:00 PM',
    courierName: 'BlueDart Bio-Express',
    courierContact: '+91 98888 12345',
    vehicleNo: 'HR-26-CD-9012',
    temperature: '3.5°C',
    timeline: [
      { step: 'Order Placed & Verified', date: '2024-08-28 10:30', completed: true, details: 'Exchange terms accepted by Fortis.' },
      { step: 'Awaiting Payment Settlement', date: '2024-08-28 11:00', completed: false, details: 'Pending buyer payment authorization.' },
      { step: 'Dispatched & Cold Seal Applied', date: 'Pending', completed: false, details: 'Packaging in insulated dry ice container.' },
      { step: 'In Transit', date: 'Pending', completed: false, details: 'Flight cargo scheduled from DEL to BOM.' },
      { step: 'Delivered', date: 'Pending', completed: false, details: 'Dock inspection required.' },
    ],
    coordinates: {
      origin: [28.4595, 77.0266], // Gurgaon
      current: [28.4595, 77.0266],
      destination: [19.0144, 73.0408],
    }
  },
  {
    transactionId: 'TXN-770412',
    trackingNumber: 'SMS-EXP-77041',
    senderHospital: 'Tata Memorial Centre (Parel, Mumbai)',
    receiverHospital: 'Apollo Hospital (Belapur, Navi Mumbai)',
    medicineName: 'Rituximab (Ristova) 500mg',
    quantity: 4,
    status: 'In Transit',
    currentLocation: 'Eastern Freeway Chembur Elevated Expressway',
    destination: 'Apollo Hospital Central Pharmacy Intake Dock',
    eta: 'Today, 04:15 PM (Est. 45 mins)',
    courierName: 'BioCold Medical Transits Mumbai',
    courierContact: '+91 98209 11445 (Driver: Vijay Shinde)',
    vehicleNo: 'MH-01-DR-3388 (IoT Active)',
    temperature: '3.8°C (Strict Cold-Chain Compliant)',
    timeline: [
      { step: 'Order Placed & Verified', date: '2024-08-28 08:30', completed: true, details: 'Verified by Tata Memorial Oncology Dispatch.' },
      { step: 'Payment Processed via Escrow', date: '2024-08-28 09:15', completed: true, details: 'Ref: pay_Rtx99120aK8, ₹2,46,000 in escrow.' },
      { step: 'Dispatched & Cold Seal Applied', date: '2024-08-28 14:00', completed: true, details: 'Cryo-insulated cold box with continuous logger.' },
      { step: 'In Transit with Live IoT GPS/Temp', date: '2024-08-28 15:10', completed: true, details: 'Chembur Freeway Checkpoint, Temp 3.8°C.' },
      { step: 'Delivered to Receiving Hospital', date: 'Pending', completed: false, details: 'Expected delivery at Belapur pharmacy intake.' },
    ],
    coordinates: {
      origin: [19.0034, 72.8427], // Parel, Mumbai
      current: [19.0522, 72.8994], // Chembur
      destination: [19.0144, 73.0408], // Belapur
    }
  },
  {
    transactionId: 'TXN-663190',
    trackingNumber: 'SMS-EXP-66319',
    senderHospital: 'Lilavati Hospital & Research Centre (Bandra)',
    receiverHospital: 'Apollo Hospital (Navi Mumbai)',
    medicineName: 'Streptokinase 1,500,000 IU',
    quantity: 12,
    status: 'In Transit',
    currentLocation: 'Sion-Panvel Expressway, Vashi Toll Plaza',
    destination: 'Apollo Hospital Cardiac Cath Lab Dock',
    eta: 'Today, 05:00 PM (Est. 30 mins)',
    courierName: 'MediExpress Cryo Transit',
    courierContact: '+91 97690 88219 (Driver: Santosh Jadhav)',
    vehicleNo: 'MH-02-CP-9912',
    temperature: '4.5°C (Compliant)',
    timeline: [
      { step: 'Order Placed & Verified', date: '2024-08-28 11:00', completed: true, details: 'Requisition approved by Lilavati Chief Pharmacist.' },
      { step: 'Payment Processed via Escrow', date: '2024-08-28 11:45', completed: true, details: 'Ref: pay_Stk88190bM2, ₹14,400 settled.' },
      { step: 'Dispatched & Cold Seal Applied', date: '2024-08-28 15:30', completed: true, details: 'Packed in vacuum-insulated panels with ice packs.' },
      { step: 'In Transit with Live IoT GPS/Temp', date: '2024-08-28 16:15', completed: true, details: 'Vashi Bridge Toll crossing.' },
      { step: 'Delivered to Receiving Hospital', date: 'Pending', completed: false, details: 'Immediate transfer to Cath Lab.' },
    ],
    coordinates: {
      origin: [19.0522, 72.8277], // Bandra
      current: [19.0771, 72.9986], // Vashi
      destination: [19.0144, 73.0408], // Belapur
    }
  },
  {
    transactionId: 'TXN-331902',
    trackingNumber: 'SMS-EXP-33190',
    senderHospital: 'Tata Memorial Centre (Mumbai)',
    receiverHospital: 'Fortis Memorial Research Institute (Gurgaon)',
    medicineName: 'Bevacizumab (Avastin) 400mg',
    quantity: 3,
    status: 'Delivered',
    currentLocation: 'Delivered - Fortis Central Drug Store, Gurgaon',
    destination: 'Fortis Oncology Pharmacy Wing',
    eta: 'Delivered on 2024-08-26 11:40 AM',
    courierName: 'BlueDart Aviation Cold-Chain Express',
    courierContact: '+91 98111 22334',
    vehicleNo: 'Flight BD-502 / Van HR-26-EE-1109',
    temperature: '4.0°C (100% In-Range Throughout)',
    timeline: [
      { step: 'Order Placed & Verified', date: '2024-08-24 10:00', completed: true, details: 'Inter-state redistribution certified.' },
      { step: 'Payment Processed via Escrow', date: '2024-08-24 12:30', completed: true, details: 'Ref: pay_Bvz44190xT1, ₹1,36,500 settled.' },
      { step: 'Dispatched & Air Freight Sealed', date: '2024-08-25 06:00', completed: true, details: 'Direct BOM-DEL refrigerated air-cargo.' },
      { step: 'In Transit & Last Mile Delivery', date: '2024-08-26 09:15', completed: true, details: 'Gurgaon delivery van, Temp 3.9°C.' },
      { step: 'Delivered & Signed Off by Pharmacist', date: '2024-08-26 11:40', completed: true, details: 'Received by Dr. Sunita Deshmukh. Zero deviation.' },
    ],
    coordinates: {
      origin: [19.0034, 72.8427], // Mumbai
      current: [28.4595, 77.0266], // Gurgaon
      destination: [28.4595, 77.0266],
    }
  }
];

export const INITIAL_PAYMENTS = [
  {
    id: 'pay-001',
    transactionId: 'TXN-773120',
    medicineName: 'Enoxaparin Sodium 40mg Prefilled Syringe',
    quantity: 50,
    amount: 18000,
    gstAmount: 2160,
    totalPaid: 20160,
    paymentStatus: 'Success',
    date: '2024-08-26 09:45 AM',
    razorpayPaymentId: 'pay_Nz8849qK91Xza',
    razorpayOrderId: 'order_Nx7712398a',
    paymentMethod: 'UPI / Razorpay Business (HDFC)',
    buyerHospital: 'Apollo Hospital (Mumbai)',
    sellerHospital: 'Max Super Speciality Hospital (Delhi)',
  },
  {
    id: 'pay-002',
    transactionId: 'TXN-661209',
    medicineName: 'Human Albumin 20% 100ml Infusion',
    quantity: 15,
    amount: 50400,
    gstAmount: 6048,
    totalPaid: 56448,
    paymentStatus: 'Success',
    date: '2024-08-14 03:20 PM',
    razorpayPaymentId: 'pay_My9921bK44Pqm',
    razorpayOrderId: 'order_Mx5544123b',
    paymentMethod: 'Corporate NetBanking (ICICI)',
    buyerHospital: 'Apollo Hospital (Mumbai)',
    sellerHospital: 'Fortis Memorial Research Institute',
  },
  {
    id: 'pay-003',
    transactionId: 'TXN-331092',
    medicineName: 'Trastuzumab (Herclon) 440mg',
    quantity: 4,
    amount: 172800,
    gstAmount: 20736,
    totalPaid: 193536,
    paymentStatus: 'Failed',
    date: '2024-08-20 08:45 AM',
    razorpayPaymentId: 'pay_Kx1198fL00Rrr',
    razorpayOrderId: 'order_Kx1122334c',
    paymentMethod: 'Bank Wire Transfer',
    buyerHospital: 'Apollo Hospital (Mumbai)',
    sellerHospital: 'Max Super Speciality Hospital',
  },
  {
    id: 'pay-004',
    transactionId: 'TXN-984210',
    medicineName: 'Meropenem Injection 1g IV Vial',
    quantity: 20,
    amount: 24050,
    gstAmount: 2886,
    totalPaid: 26936,
    paymentStatus: 'Pending',
    date: '2024-08-28 10:35 AM',
    razorpayPaymentId: 'Awaiting Initiation',
    razorpayOrderId: 'order_Ot9944111d',
    paymentMethod: 'Pending Checkout',
    buyerHospital: 'Apollo Hospital (Mumbai)',
    sellerHospital: 'Fortis Memorial Research Institute',
  },
  {
    id: 'pay-005',
    transactionId: 'TXN-672418',
    medicineName: 'Ceftriaxone Sodium 1g Injection',
    quantity: 80,
    amount: 18400,
    gstAmount: 2208,
    totalPaid: 20608,
    paymentStatus: 'Success',
    date: '2024-08-27 02:15 PM',
    razorpayPaymentId: 'pay_Px8832cL17Taa',
    razorpayOrderId: 'order_Px5588214b',
    paymentMethod: 'Razorpay Escrow Settlement',
    buyerHospital: 'Fortis Memorial Research Institute',
    sellerHospital: 'Apollo Hospital (Mumbai)',
  },
  {
    id: 'pay-006',
    transactionId: 'TXN-718305',
    medicineName: 'Vancomycin Hydrochloride 500mg Vial',
    quantity: 30,
    amount: 12600,
    gstAmount: 1512,
    totalPaid: 14112,
    paymentStatus: 'Success',
    date: '2024-08-22 11:05 AM',
    razorpayPaymentId: 'pay_Qx4417dM29Kbb',
    razorpayOrderId: 'order_Qx3309127c',
    paymentMethod: 'Corporate NetBanking (ICICI)',
    buyerHospital: 'Max Super Speciality Hospital (Delhi)',
    sellerHospital: 'Apollo Hospital (Mumbai)',
  },
  {
    id: 'pay-007',
    transactionId: 'TXN-770412',
    medicineName: 'Rituximab (Ristova) 500mg',
    quantity: 4,
    amount: 246000,
    gstAmount: 29520,
    totalPaid: 275520,
    paymentStatus: 'Success',
    date: '2024-08-28 09:15 AM',
    razorpayPaymentId: 'pay_Rtx99120aK8',
    razorpayOrderId: 'order_Rt990145a',
    paymentMethod: 'Corporate Escrow (HDFC SmartHub)',
    buyerHospital: 'Apollo Hospital (Mumbai)',
    sellerHospital: 'Tata Memorial Centre',
  },
  {
    id: 'pay-008',
    transactionId: 'TXN-663190',
    medicineName: 'Streptokinase 1,500,000 IU',
    quantity: 12,
    amount: 14400,
    gstAmount: 1728,
    totalPaid: 16128,
    paymentStatus: 'Success',
    date: '2024-08-28 11:45 AM',
    razorpayPaymentId: 'pay_Stk88190bM2',
    razorpayOrderId: 'order_St881023b',
    paymentMethod: 'Razorpay Instant Settlement',
    buyerHospital: 'Apollo Hospital (Mumbai)',
    sellerHospital: 'Lilavati Hospital & Research Centre',
  },
  {
    id: 'pay-009',
    transactionId: 'TXN-331902',
    medicineName: 'Bevacizumab (Avastin) 400mg',
    quantity: 3,
    amount: 136500,
    gstAmount: 16380,
    totalPaid: 152880,
    paymentStatus: 'Success',
    date: '2024-08-24 12:30 PM',
    razorpayPaymentId: 'pay_Bvz44190xT1',
    razorpayOrderId: 'order_Bv441092c',
    paymentMethod: 'Corporate NetBanking (SBI Global)',
    buyerHospital: 'Fortis Memorial Research Institute (Gurgaon)',
    sellerHospital: 'Tata Memorial Centre (Mumbai)',
  },
  {
    id: 'pay-010',
    transactionId: 'TXN-550912',
    medicineName: 'Propofol Injection 1% 20ml Vial',
    quantity: 40,
    amount: 9880,
    gstAmount: 1185.6,
    totalPaid: 11065.6,
    paymentStatus: 'Pending',
    date: '2024-08-28 01:20 PM',
    razorpayPaymentId: 'Awaiting Authorization',
    razorpayOrderId: 'order_Pf5509129e',
    paymentMethod: 'Corporate NetBanking (Axis Bank)',
    buyerHospital: 'Lilavati Hospital & Research Centre',
    sellerHospital: 'Apollo Hospital (Mumbai)',
  },
  {
    id: 'pay-011',
    transactionId: 'TXN-442819',
    medicineName: 'Insulin Glargine (Lantus) SoloStar',
    quantity: 25,
    amount: 15575,
    gstAmount: 1869,
    totalPaid: 17444,
    paymentStatus: 'Success',
    date: '2024-08-28 03:40 PM',
    razorpayPaymentId: 'pay_Lnt442819kL9',
    razorpayOrderId: 'order_Lt4428191z',
    paymentMethod: 'UPI / Razorpay Business (ICICI)',
    buyerHospital: 'Max Super Speciality Hospital (Delhi)',
    sellerHospital: 'Apollo Hospital (Mumbai)',
  },
  {
    id: 'pay-012',
    transactionId: 'TXN-884019',
    medicineName: 'Heparin Sodium 25,000 IU',
    quantity: 60,
    amount: 23400,
    gstAmount: 2808,
    totalPaid: 26208,
    paymentStatus: 'Pending',
    date: '2024-08-28 04:10 PM',
    razorpayPaymentId: 'Awaiting Initiation',
    razorpayOrderId: 'order_Hp8840198q',
    paymentMethod: 'Pending Checkout',
    buyerHospital: 'Kokilaben Dhirubhai Ambani Hospital',
    sellerHospital: 'Apollo Hospital (Mumbai)',
  }
];

export const INITIAL_DISPOSALS = [
  {
    id: 'disp-301',
    hospitalId: 'hosp-1',
    hospitalName: 'Apollo Hospital',
    medicineId: 'med-105',
    medicineName: 'Cefotaxime Sodium 500mg (Expired)',
    wasteCategory: 'Expired Pharmaceuticals',
    batchNo: 'CF500-112',
    quantity: '150 Vials (12.5 kg)',
    expiryDate: '2024-06-30',
    reason: 'Statutory Shelf-Life Expiration past CDSCO buffer',
    preferredPickupDate: '2024-07-02',
    pickupDate: '2024-07-03',
    bioCentreName: 'Maharashtra Enviro Power Bio-Medical Waste Plant',
    bioCentreAddress: 'Plot P-32, MIDC Taloja, Raigad, Maharashtra 410208',
    vehicleNo: 'MH-04-GP-8833',
    driverContact: '+91 97654 32109 (Mahesh K.)',
    currentLocation: 'Taloja MIDC High-Temperature Rotary Incinerator',
    eta: 'Completed (Incineration Done)',
    status: 'Incinerated & Certified',
    certificateNo: 'BMW-INC-2024-88712',
    certificateDate: '2024-07-04',
    treatmentMethod: 'High-Temperature Double-Chamber Rotary Incineration (1100°C)',
    manifestNumber: 'MPCB-BMW-MNF-99412',
  },
  {
    id: 'disp-302',
    hospitalId: 'hosp-3',
    hospitalName: 'Max Super Speciality Hospital',
    medicineId: 'med-104',
    medicineName: 'Oxytocin Injection 10 IU (Compromised Cold Chain)',
    wasteCategory: 'Cold-Chain Failure / Biologicals',
    batchNo: 'OXY-908',
    quantity: '80 Ampoules (3.2 kg)',
    expiryDate: '2024-07-15',
    reason: 'Cold chain transit breach (> 14°C for 6h)',
    preferredPickupDate: '2024-07-20',
    pickupDate: '2024-07-21',
    bioCentreName: 'Delhi Central Bio-Medical Incinerator, Okhla',
    bioCentreAddress: 'Okhla Industrial Area Phase-I, New Delhi 110020',
    vehicleNo: 'DL-01-EA-5541',
    driverContact: '+91 98100 45678 (Suresh Pal)',
    currentLocation: 'Mathura Road Transit Hub',
    eta: 'In Transit to Bio-Centre',
    status: 'In Transit to Bio-Centre',
    certificateNo: null,
    certificateDate: null,
    treatmentMethod: 'Autoclaving + Shredding followed by Secured Landfill',
    manifestNumber: 'DPCC-BMW-MNF-66231',
  },
  {
    id: 'disp-303',
    hospitalId: 'hosp-2',
    hospitalName: 'Fortis Memorial Research Institute',
    medicineId: 'med-103',
    medicineName: 'Chemotherapy Cisplatin Residues (Cytotoxic)',
    wasteCategory: 'Cytotoxic & Hazardous Oncology Waste',
    batchNo: 'CIS-4410',
    quantity: '18 Vials Hazardous Cytotoxic (4.0 kg)',
    expiryDate: '2024-07-31',
    reason: 'Partially consumed surgical cytotoxic residue',
    preferredPickupDate: '2024-08-05',
    pickupDate: '2024-08-06',
    bioCentreName: 'Haryana State Bio-Hazard Incineration Facility',
    bioCentreAddress: 'IMT Manesar Sector 8, Gurugram, Haryana 122051',
    vehicleNo: 'HR-55-ZX-9922',
    driverContact: '+91 99912 34567 (Joginder Singh)',
    currentLocation: 'Fortis Basement Bio-Waste Holding Cell',
    eta: 'Scheduled Pickup: Tomorrow 10:00 AM',
    status: 'Pickup Scheduled',
    certificateNo: null,
    certificateDate: null,
    treatmentMethod: 'High-Temperature Plasma Gasification (1200°C)',
    manifestNumber: 'HSPCB-BMW-MNF-44109',
  },
  {
    id: 'disp-304',
    hospitalId: 'hosp-7',
    hospitalName: 'Tata Memorial Centre',
    medicineId: 'med-129',
    medicineName: 'Paclitaxel & Doxorubicin Infusion Remnants (Cytotoxic)',
    wasteCategory: 'Cytotoxic & Hazardous Oncology Waste',
    batchNo: 'TAX-881',
    quantity: '24 Vials Hazardous Cytotoxic (6.8 kg)',
    expiryDate: '2024-08-15',
    reason: 'Compromised temperature during reconstitution in sterile isolator',
    preferredPickupDate: '2024-08-25',
    pickupDate: '2024-08-26',
    bioCentreName: 'Maharashtra Enviro Power Bio-Medical Waste Plant',
    bioCentreAddress: 'Plot P-32, MIDC Taloja, Raigad, Maharashtra 410208',
    vehicleNo: 'MH-04-GP-9911',
    driverContact: '+91 98332 11980 (Ramesh Patil)',
    currentLocation: 'Vashi Creek Bridge en route to Taloja',
    eta: 'In Transit to Bio-Centre (Est. 45 mins)',
    status: 'In Transit to Bio-Centre',
    certificateNo: null,
    certificateDate: null,
    treatmentMethod: 'High-Temperature Plasma Gasification & Hazardous Incineration (1200°C)',
    manifestNumber: 'MPCB-BMW-MNF-77182',
  },
  {
    id: 'disp-305',
    hospitalId: 'hosp-8',
    hospitalName: 'All India Institute of Medical Sciences (AIIMS)',
    medicineId: 'med-122',
    medicineName: 'Expired Rabies Immunoglobulin & Antisnake Venom',
    wasteCategory: 'Expired Biologicals & Vaccines',
    batchNo: 'RIG-441',
    quantity: '50 Vials (8.5 kg)',
    expiryDate: '2024-07-31',
    reason: 'Statutory batch shelf-life expired past CDSCO emergency window',
    preferredPickupDate: '2024-08-20',
    pickupDate: '2024-08-21',
    bioCentreName: 'Biotic Waste Solutions Pvt. Ltd., Okhla',
    bioCentreAddress: '46 Okhla Industrial Area Phase-II, New Delhi 110020',
    vehicleNo: 'DL-1L-AB-2290',
    driverContact: '+91 98114 77201 (Satinder Singh)',
    currentLocation: 'Biotic Waste Solutions Incinerator Complex',
    eta: 'Completed (Incineration Done)',
    status: 'Incinerated & Certified',
    certificateNo: 'BMW-INC-2024-99415',
    certificateDate: '2024-08-22',
    treatmentMethod: 'High-Temperature Dual-Chamber Controlled Air Incineration (1050°C)',
    manifestNumber: 'DPCC-BMW-MNF-88190',
  },
  {
    id: 'disp-306',
    hospitalId: 'hosp-5',
    hospitalName: 'Lilavati Hospital & Research Centre',
    medicineId: 'med-113',
    medicineName: 'Propofol & Atracurium Expired Sedative Residues',
    wasteCategory: 'Expired Controlled Anesthetics',
    batchNo: 'PRO-220',
    quantity: '110 Ampoules (4.2 kg)',
    expiryDate: '2024-08-10',
    reason: 'OT buffer batch shelf-life exceeded',
    preferredPickupDate: '2024-08-29',
    pickupDate: '2024-08-30',
    bioCentreName: 'SMS Envoclean Bio-Medical Waste Facility',
    bioCentreAddress: 'Deonar Dumping Ground Road, Govandi East, Mumbai 400043',
    vehicleNo: 'MH-03-CB-6612',
    driverContact: '+91 98205 33491 (Ganesh More)',
    currentLocation: 'Lilavati Hospital Holding Cell B-2',
    eta: 'Pickup Scheduled: Tomorrow 09:30 AM',
    status: 'Pickup Scheduled',
    certificateNo: null,
    certificateDate: null,
    treatmentMethod: 'High-Pressure Steam Autoclaving + Controlled Shredding',
    manifestNumber: 'MPCB-BMW-MNF-33104',
  },
  {
    id: 'disp-307',
    hospitalId: 'hosp-9',
    hospitalName: 'Kokilaben Dhirubhai Ambani Hospital',
    medicineId: 'med-125',
    medicineName: 'Damaged Dialysis Heparin Lines & Contaminated Vials',
    wasteCategory: 'Contaminated Biomedical Consumables',
    batchNo: 'DIA-994',
    quantity: '45 Units (18.0 kg)',
    expiryDate: '2024-08-20',
    reason: 'Mechanical package tear during nephrology ward delivery',
    preferredPickupDate: '2024-08-30',
    pickupDate: null,
    bioCentreName: 'SMS Envoclean Bio-Medical Waste Facility',
    bioCentreAddress: 'Deonar Dumping Ground Road, Govandi East, Mumbai 400043',
    vehicleNo: 'Assigned upon confirmation',
    driverContact: 'Pending dispatch',
    currentLocation: 'Kokilaben Basement Bio-Hazard Segregation Bay',
    eta: 'Awaiting CPCB Registered Vehicle Assignment',
    status: 'Reported',
    certificateNo: null,
    certificateDate: null,
    treatmentMethod: 'Autoclaving + Microwaving + Deep Burial / Encapsulation',
    manifestNumber: 'MPCB-BMW-MNF-11984',
  },
  {
    id: 'disp-308',
    hospitalId: 'hosp-1',
    hospitalName: 'Apollo Hospital',
    medicineId: 'med-124',
    medicineName: 'Colistimethate Sodium Expired Polymyxin Vials',
    wasteCategory: 'Expired Critical Care Antibiotics',
    batchNo: 'COL-009',
    quantity: '60 Vials (3.8 kg)',
    expiryDate: '2024-07-28',
    reason: 'Statutory expiration - antimicrobial stewardship non-usable stock',
    preferredPickupDate: '2024-08-31',
    pickupDate: null,
    bioCentreName: 'Maharashtra Enviro Power Bio-Medical Waste Plant',
    bioCentreAddress: 'Plot P-32, MIDC Taloja, Raigad, Maharashtra 410208',
    vehicleNo: 'Assigned upon confirmation',
    driverContact: 'Pending dispatch',
    currentLocation: 'Apollo Hospital Central Pharmacy Bio-Waste Locker',
    eta: 'Reported - Verification by State Pollution Control Board Pending',
    status: 'Reported',
    certificateNo: null,
    certificateDate: null,
    treatmentMethod: 'High-Temperature Double-Chamber Rotary Incineration (1100°C)',
    manifestNumber: 'MPCB-BMW-MNF-44189',
  }
];

export const INITIAL_FEEDBACKS = [
  {
    id: 'fb-401',
    hospitalId: 'hosp-2',
    hospitalName: 'Fortis Memorial Research Institute',
    rating: 5,
    category: 'Logistics & Cold-Chain',
    feedbackText: 'The cold chain validation and real-time temperature loggers on SmartMediShare are extraordinary. Saved over ₹3.4 Lakhs on near-expiry oncology supplies.',
    date: '2024-08-27',
    adminReply: 'Thank you Dr. Deshmukh. Our temperature telemetry integration ensures zero spoilage during transport.',
    repliedDate: '2024-08-28',
  },
  {
    id: 'fb-402',
    hospitalId: 'hosp-3',
    hospitalName: 'Max Super Speciality Hospital',
    rating: 4,
    category: 'Inventory Concession Calculator',
    feedbackText: 'The automated concession calculator based on shelf-life months is very intuitive. Would love an option to auto-match bulk buyers in neighbouring districts.',
    date: '2024-08-25',
    adminReply: 'Appreciate your feedback! District-level automated smart matching is rolling out in next sprint.',
    repliedDate: '2024-08-26',
  },
  {
    id: 'fb-403',
    hospitalId: 'hosp-1',
    hospitalName: 'Apollo Hospital',
    rating: 5,
    category: 'Platform Verification & Security',
    feedbackText: 'Fast onboarding and seamless Razorpay mock gateway testing. The compliance documentation audit gives complete peace of mind for Schedule H drugs.',
    date: '2024-08-29',
    adminReply: null,
    repliedDate: null,
  },
  {
    id: 'fb-404',
    hospitalId: 'hosp-7',
    hospitalName: 'Tata Memorial Centre',
    rating: 5,
    category: 'Oncology Drug Preservation',
    feedbackText: 'SmartMediShare helped us prevent ₹8.2 Lakhs of high-value immunotherapy medicines from expiring unused. Seamless escrow-backed payments and real-time cold-chain tracking give total confidence.',
    date: '2024-08-28',
    adminReply: 'Dr. Badwe, we are honored to support Tata Memorial Centre. Ensuring critical oncology molecules reach patients in time is our core mission.',
    repliedDate: '2024-08-28',
  },
  {
    id: 'fb-405',
    hospitalId: 'hosp-8',
    hospitalName: 'All India Institute of Medical Sciences (AIIMS)',
    rating: 5,
    category: 'Inter-State Hospital Redistribution',
    feedbackText: 'Redistributing life-saving Liposomal Amphotericin B and emergency ICU reserves across northern states within 24 hours was unthinkable earlier. The 48-hour SLA mechanism prevents hoarding.',
    date: '2024-08-29',
    adminReply: 'Thank you AIIMS pharmacy procurement team. The automated timer has dramatically accelerated response times.',
    repliedDate: '2024-08-29',
  },
  {
    id: 'fb-406',
    hospitalId: 'hosp-5',
    hospitalName: 'Lilavati Hospital & Research Centre',
    rating: 4,
    category: 'Bio-Medical Waste & CPCB Compliance',
    feedbackText: 'The Form-IV bio-waste disposal module with instant manifest generation and certificate repository makes annual MPCB audits completely hassle-free.',
    date: '2024-08-28',
    adminReply: 'Glad to hear! We are adding automated annual CPCB Form-IV filing exports in the upcoming release.',
    repliedDate: '2024-08-28',
  },
  {
    id: 'fb-407',
    hospitalId: 'hosp-9',
    hospitalName: 'Kokilaben Dhirubhai Ambani Hospital',
    rating: 5,
    category: 'Dual Requisition / Competing Request Engine',
    feedbackText: 'The first-acceptance-wins logic is brilliant. When managing critical ICU shortages, we no longer need to make sequential phone calls to peer hospitals.',
    date: '2024-08-29',
    adminReply: null,
    repliedDate: null,
  }
];

export const HOSPITAL_ANALYTICS = {
  stats: {
    totalMedicines: 184,
    monthlyPurchases: 462500,
    monthlySales: 689000,
    profitabilityPercent: 28.4,
    medicinesSaved: 1420,
    activeTransfers: 3,
  },
  purchasesMonthly: [
    { month: 'Mar', amount: 320000, units: 140 },
    { month: 'Apr', amount: 410000, units: 185 },
    { month: 'May', amount: 380000, units: 160 },
    { month: 'Jun', amount: 490000, units: 210 },
    { month: 'Jul', amount: 440000, units: 195 },
    { month: 'Aug', amount: 462500, units: 205 },
  ],
  salesMonthly: [
    { month: 'Mar', amount: 480000, units: 220 },
    { month: 'Apr', amount: 530000, units: 245 },
    { month: 'May', amount: 590000, units: 280 },
    { month: 'Jun', amount: 620000, units: 290 },
    { month: 'Jul', amount: 645000, units: 310 },
    { month: 'Aug', amount: 689000, units: 340 },
  ],
  profitabilityTrend: [
    { month: 'Apr', revenue: 530000, cost: 410000, marginPercent: 22.6 },
    { month: 'May', revenue: 590000, cost: 380000, marginPercent: 35.5 },
    { month: 'Jun', revenue: 620000, cost: 490000, marginPercent: 20.9 },
    { month: 'Jul', revenue: 645000, cost: 440000, marginPercent: 31.7 },
    { month: 'Aug', revenue: 689000, cost: 462500, marginPercent: 32.8 },
  ]
};

export const ADMIN_ANALYTICS = {
  stats: {
    totalHospitals: 48,
    monthlyTransfers: 324,
    totalMedicinesTransferred: 18450,
    totalPlatformVolume: '₹ 1.84 Cr',
    wastagePreventedTons: '14.2 Tons',
    avgFulfillmentRate: '98.4%',
  },
  transferTrends: [
    { month: 'Mar', transfers: 180, volumeINR: 980000 },
    { month: 'Apr', transfers: 220, volumeINR: 1250000 },
    { month: 'May', transfers: 260, volumeINR: 1480000 },
    { month: 'Jun', transfers: 290, volumeINR: 1620000 },
    { month: 'Jul', transfers: 310, volumeINR: 1740000 },
    { month: 'Aug', transfers: 324, volumeINR: 1840000 },
  ],
  systemPerformance: [
    { metric: 'Fulfillment Rate', score: 98.4, target: 95 },
    { metric: 'Cold-Chain Integrity', score: 99.1, target: 98 },
    { metric: 'Avg Transit Speed (h)', score: 92.5, target: 90 },
    { metric: 'Verification Turnaround', score: 96.0, target: 90 },
    { metric: 'Disposal Compliance', score: 100.0, target: 100 },
  ],
  topHotMedicines: [
    { name: 'Meropenem 1g', exchanges: 420, valueLakhs: 7.77 },
    { name: 'Enoxaparin 40mg', exchanges: 390, valueLakhs: 1.87 },
    { name: 'Human Albumin 20%', exchanges: 310, valueLakhs: 13.02 },
    { name: 'Remdesivir 100mg', exchanges: 280, valueLakhs: 7.84 },
    { name: 'Augmentin 625mg', exchanges: 240, valueLakhs: 0.50 },
    { name: 'Pantoprazole 40mg', exchanges: 215, valueLakhs: 0.14 },
    { name: 'Trastuzumab 440mg', exchanges: 195, valueLakhs: 105.3 },
    { name: 'Insulin Glargine', exchanges: 180, valueLakhs: 1.60 },
    { name: 'Ceftriaxone 1g', exchanges: 165, valueLakhs: 0.12 },
    { name: 'Noradrenaline 2mg', exchanges: 150, valueLakhs: 0.28 },
  ]
};
