export const INITIAL_HOSPITALS = [
  {
    id: 'hosp-1',
    name: 'Apollo Hospital',
    registrationNo: 'MH-MUM-2018-8821',
    authorizedPerson: 'Dr. Rajesh Sharma (Chief Pharmacist)',
    email: 'apollo.mumbai@smartmedishare.org',
    phone: '+91 98201 54321',
    address: 'Plot No. 13, Sector 23, Off CBD Belapur Road',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400614',
    status: 'verified',
    registeredDate: '2024-01-15',
    verifiedDate: '2024-01-16',
    documents: [
      { name: 'Hospital_Registration_Cert.pdf', size: '2.4 MB', type: 'Registration Certificate', verified: true },
      { name: 'Drug_License_Form20B_21B.pdf', size: '3.1 MB', type: 'Drug License', verified: true },
      { name: 'GST_Registration_Certificate.pdf', size: '1.2 MB', type: 'GST Certificate', verified: true },
      { name: 'Director_Authorization_Letter.pdf', size: '1.8 MB', type: 'Authorization Letter', verified: true },
    ],
  },
  {
    id: 'hosp-2',
    name: 'Fortis Memorial Research Institute',
    registrationNo: 'HR-GUR-2019-4412',
    authorizedPerson: 'Dr. Sunita Deshmukh (Procurement Lead)',
    email: 'fortis.gurgaon@smartmedishare.org',
    phone: '+91 98112 33445',
    address: 'Sector 44, Opposite HUDA City Centre Metro',
    city: 'Gurgaon',
    state: 'Haryana',
    pincode: '122002',
    status: 'verified',
    registeredDate: '2024-02-10',
    verifiedDate: '2024-02-12',
    documents: [
      { name: 'Fortis_Hospital_Reg.pdf', size: '4.2 MB', type: 'Registration Certificate', verified: true },
      { name: 'Pharmacy_Retail_Wholesale_Lic.pdf', size: '2.8 MB', type: 'Drug License', verified: true },
      { name: 'GST_Compliance_2024.pdf', size: '1.5 MB', type: 'GST Certificate', verified: true },
      { name: 'Board_Resolution_MediShare.pdf', size: '1.1 MB', type: 'Authorization Letter', verified: true },
    ],
  },
  {
    id: 'hosp-3',
    name: 'Max Super Speciality Hospital',
    registrationNo: 'DL-SAK-2020-9011',
    authorizedPerson: 'Dr. Amitav Roy (Director Operations)',
    email: 'max.saket@smartmedishare.org',
    phone: '+91 99100 87654',
    address: '1, 2, Press Enclave Marg, Saket',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110017',
    status: 'verified',
    registeredDate: '2024-03-05',
    verifiedDate: '2024-03-07',
    documents: [
      { name: 'Max_Health_RegDoc.pdf', size: '3.6 MB', type: 'Registration Certificate', verified: true },
      { name: 'Drug_Inspector_Approved_Lic.pdf', size: '2.9 MB', type: 'Drug License', verified: true },
      { name: 'GST_Saket_Max.pdf', size: '1.4 MB', type: 'GST Certificate', verified: true },
      { name: 'Authorized_Signatory_Roy.pdf', size: '1.9 MB', type: 'Authorization Letter', verified: true },
    ],
  },
  {
    id: 'hosp-4',
    name: 'Manipal Hospital',
    registrationNo: 'KA-BLR-2021-3320',
    authorizedPerson: 'Dr. Anand Kumar (Head of Inventory)',
    email: 'manipal.blr@smartmedishare.org',
    phone: '+91 97411 22334',
    address: '98, HAL Old Airport Rd, Kodihalli',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560017',
    status: 'pending',
    registeredDate: '2024-08-28',
    verifiedDate: null,
    documents: [
      { name: 'Manipal_Establishment_Act_Doc.pdf', size: '5.1 MB', type: 'Registration Certificate', verified: false },
      { name: 'Form20_Pharmacy_Permit.pdf', size: '3.4 MB', type: 'Drug License', verified: false },
      { name: 'Karnataka_GST_Manipal.pdf', size: '1.7 MB', type: 'GST Certificate', verified: false },
      { name: 'MD_Power_of_Attorney.pdf', size: '2.2 MB', type: 'Authorization Letter', verified: false },
    ],
  },
  {
    id: 'hosp-5',
    name: 'Lilavati Hospital & Research Centre',
    registrationNo: 'MH-MUM-2017-1099',
    authorizedPerson: 'Dr. Priya Merchant (Pharmacy Head)',
    email: 'lilavati.mumbai@smartmedishare.org',
    phone: '+91 98211 44556',
    address: 'A-791, Bandra Reclamation, Bandra West',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400050',
    status: 'pending',
    registeredDate: '2024-08-30',
    verifiedDate: null,
    documents: [
      { name: 'Lilavati_Registration_Doc.pdf', size: '4.8 MB', type: 'Registration Certificate', verified: false },
      { name: 'Drug_Authority_Approval.pdf', size: '2.6 MB', type: 'Drug License', verified: false },
      { name: 'GSTIN_MH_Lilavati.pdf', size: '1.3 MB', type: 'GST Certificate', verified: false },
      { name: 'Authorization_DrMerchant.pdf', size: '1.5 MB', type: 'Authorization Letter', verified: false },
    ],
  },
  {
    id: 'hosp-6',
    name: 'Medanta - The Medicity',
    registrationNo: 'HR-GUR-2022-7714',
    authorizedPerson: 'Dr. Vikram Malhotra (Medical Superintendent)',
    email: 'medanta.gurgaon@smartmedishare.org',
    phone: '+91 99990 11223',
    address: 'CH Bakhtawar Singh Rd, Sector 38',
    city: 'Gurgaon',
    state: 'Haryana',
    pincode: '122001',
    status: 'rejected',
    registeredDate: '2024-08-15',
    verifiedDate: null,
    rejectionReason: 'GST document expired and drug storage temperature logs missing for schedule H1 compliance.',
    documents: [
      { name: 'Medanta_Reg_Old.pdf', size: '3.1 MB', type: 'Registration Certificate', verified: false },
      { name: 'Drug_Lic_2022.pdf', size: '2.0 MB', type: 'Drug License', verified: false },
    ],
  }
];

export const INITIAL_MEDICINES = [
  {
    id: 'med-101',
    brandName: 'Meropenem Injection',
    genericName: 'Meropenem Trihydrate IP',
    power: '1g IV Vial',
    category: 'Critical Care / Antibiotic',
    storageType: 'Cold Storage (2°C - 8°C)',
    mfgDate: '2023-11-20',
    expiryDate: '2024-11-20',
    batchNo: 'MP23G418',
    manufacturer: 'AstraZeneca Healthcare',
    quantity: 45,
    unitOriginalPrice: 1850,
    concessionPercent: 35,
    hospitalId: 'hosp-2',
    hospitalName: 'Fortis Memorial Research Institute',
    location: 'Gurgaon, Haryana',
    distanceKm: 14.5,
    dateAdded: '2024-08-01',
    notes: 'Stored in certified cold chain facility, seal intact.',
  },
  {
    id: 'med-102',
    brandName: 'Enoxaparin Sodium',
    genericName: 'Clexane Anti-coagulant',
    power: '40mg / 0.4ml Prefilled Syringe',
    category: 'Cardiology / Hematology',
    storageType: 'Room Temperature (15°C - 25°C)',
    mfgDate: '2023-12-15',
    expiryDate: '2024-12-15',
    batchNo: 'CX88902',
    manufacturer: 'Sanofi India Ltd',
    quantity: 120,
    unitOriginalPrice: 480,
    concessionPercent: 25,
    hospitalId: 'hosp-3',
    hospitalName: 'Max Super Speciality Hospital',
    location: 'New Delhi, Delhi',
    distanceKm: 22.0,
    dateAdded: '2024-08-05',
    notes: 'Surplus surgical inventory from cardiac unit.',
  },
  {
    id: 'med-103',
    brandName: 'Human Albumin 20%',
    genericName: 'Human Albumin Solution USP',
    power: '100ml Infusion Bottle',
    category: 'Emergency / Plasma expander',
    storageType: 'Room Temperature (2°C - 25°C)',
    mfgDate: '2024-01-30',
    expiryDate: '2025-01-30',
    batchNo: 'ALB9941',
    manufacturer: 'Baxter Healthcare',
    quantity: 28,
    unitOriginalPrice: 4200,
    concessionPercent: 20,
    hospitalId: 'hosp-2',
    hospitalName: 'Fortis Memorial Research Institute',
    location: 'Gurgaon, Haryana',
    distanceKm: 14.5,
    dateAdded: '2024-08-10',
    notes: 'High demand plasma derivative.',
  },
  {
    id: 'med-104',
    brandName: 'Augmentin Duo',
    genericName: 'Amoxicillin + Potassium Clavulanate',
    power: '625mg Tablets (Strip of 10)',
    category: 'General / Antibiotic',
    storageType: 'Dry & Cool (<25°C)',
    mfgDate: '2024-04-15',
    expiryDate: '2025-04-15',
    batchNo: 'AG625-78',
    manufacturer: 'GlaxoSmithKline',
    quantity: 350,
    unitOriginalPrice: 210,
    concessionPercent: 15,
    hospitalId: 'hosp-3',
    hospitalName: 'Max Super Speciality Hospital',
    location: 'New Delhi, Delhi',
    distanceKm: 22.0,
    dateAdded: '2024-08-12',
    notes: 'Standard hospital pharmacy stock.',
  },
  {
    id: 'med-105',
    brandName: 'Pantoprazole IV',
    genericName: 'Pantoprazole Sodium for Inj IP',
    power: '40mg Vial',
    category: 'Gastroenterology',
    storageType: 'Room Temperature (15°C - 30°C)',
    mfgDate: '2023-10-31',
    expiryDate: '2024-10-31',
    batchNo: 'PAN40-109',
    manufacturer: 'Alkem Laboratories',
    quantity: 200,
    unitOriginalPrice: 65,
    concessionPercent: 40,
    hospitalId: 'hosp-1',
    hospitalName: 'Apollo Hospital',
    location: 'Mumbai, Maharashtra',
    distanceKm: 0,
    dateAdded: '2024-07-20',
    notes: 'Near-term batch available at steep discount.',
  },
  {
    id: 'med-106',
    brandName: 'Insulin Glargine (Lantus)',
    genericName: 'Insulin Glargine 100 IU/ml',
    power: '3ml SoloStar Pen',
    category: 'Diabetes Care',
    storageType: 'Cold Storage (2°C - 8°C)',
    mfgDate: '2023-11-15',
    expiryDate: '2024-11-15',
    batchNo: 'LT90812',
    manufacturer: 'Sanofi Healthcare',
    quantity: 60,
    unitOriginalPrice: 890,
    concessionPercent: 30,
    hospitalId: 'hosp-1',
    hospitalName: 'Apollo Hospital',
    location: 'Mumbai, Maharashtra',
    distanceKm: 0,
    dateAdded: '2024-07-25',
    notes: 'Cold storage monitored via digital IoT logger.',
  },
  {
    id: 'med-107',
    brandName: 'Ceftriaxone Injection (Monocef)',
    genericName: 'Ceftriaxone Sodium Sterile IP',
    power: '1000mg (1g) with WFI',
    category: 'Critical Care / Antibiotic',
    storageType: 'Room Temperature (15°C - 30°C)',
    mfgDate: '2024-06-20',
    expiryDate: '2025-06-20',
    batchNo: 'MC1000-88',
    manufacturer: 'Aristo Pharmaceuticals',
    quantity: 500,
    unitOriginalPrice: 75,
    concessionPercent: 12,
    hospitalId: 'hosp-1',
    hospitalName: 'Apollo Hospital',
    location: 'Mumbai, Maharashtra',
    distanceKm: 0,
    dateAdded: '2024-08-02',
    notes: 'High turnover antibiotic stock.',
  },
  {
    id: 'med-108',
    brandName: 'Remdesivir IV (Covifor)',
    genericName: 'Remdesivir Lyophilized Powder',
    power: '100mg Vial',
    category: 'Antiviral / Emergency',
    storageType: 'Room Temperature (<30°C)',
    mfgDate: '2023-10-10',
    expiryDate: '2024-10-10',
    batchNo: 'RDV-401',
    manufacturer: 'Hetero Healthcare',
    quantity: 35,
    unitOriginalPrice: 2800,
    concessionPercent: 45,
    hospitalId: 'hosp-2',
    hospitalName: 'Fortis Memorial Research Institute',
    location: 'Gurgaon, Haryana',
    distanceKm: 14.5,
    dateAdded: '2024-08-14',
    notes: 'Expiring in under 2 months, urgent redistribution.',
  },
  {
    id: 'med-109',
    brandName: 'Trastuzumab (Herclon)',
    genericName: 'Trastuzumab 440mg Lyophilized',
    power: '440mg Multi-dose Vial',
    category: 'Oncology',
    storageType: 'Cold Storage (2°C - 8°C)',
    mfgDate: '2024-02-28',
    expiryDate: '2025-02-28',
    batchNo: 'TRAST-991',
    manufacturer: 'Roche Products India',
    quantity: 8,
    unitOriginalPrice: 54000,
    concessionPercent: 20,
    hospitalId: 'hosp-3',
    hospitalName: 'Max Super Speciality Hospital',
    location: 'New Delhi, Delhi',
    distanceKm: 22.0,
    dateAdded: '2024-08-18',
    notes: 'Premium oncology monoclonal antibody.',
  },
  {
    id: 'med-110',
    brandName: 'Noradrenaline Injection',
    genericName: 'Norepinephrine Bitartrate 2mg/ml',
    power: '2ml Ampoule (Pack of 5)',
    category: 'ICU / Vasopressor',
    storageType: 'Protect from Light (<25°C)',
    mfgDate: '2023-12-30',
    expiryDate: '2024-12-30',
    batchNo: 'NAD-552',
    manufacturer: 'Neon Laboratories',
    quantity: 180,
    unitOriginalPrice: 190,
    concessionPercent: 25,
    hospitalId: 'hosp-1',
    hospitalName: 'Apollo Hospital',
    location: 'Mumbai, Maharashtra',
    distanceKm: 0,
    dateAdded: '2024-08-11',
    notes: 'Essential ICU emergency stock.',
  },
  {
    id: 'med-111',
    brandName: 'Dexamethasone Sodium Phosphate',
    genericName: 'Dexamethasone Inj 4mg/ml',
    power: '2ml Vial (Box of 20)',
    category: 'Steroids / Anti-inflammatory',
    storageType: 'Room Temperature (15°C - 30°C)',
    mfgDate: '2024-07-15',
    expiryDate: '2025-07-15',
    batchNo: 'DEX-092',
    manufacturer: 'Cadila Healthcare (Zydus)',
    quantity: 400,
    unitOriginalPrice: 140,
    concessionPercent: 15,
    hospitalId: 'hosp-2',
    hospitalName: 'Fortis Memorial Research Institute',
    location: 'Gurgaon, Haryana',
    distanceKm: 14.5,
    dateAdded: '2024-08-19',
    notes: 'Long-dated stable corticosteroid batch.',
  },
  {
    id: 'med-112',
    brandName: 'Paracetamol IV Infusion',
    genericName: 'Paracetamol 1% w/v IV',
    power: '100ml Infusion Bottle',
    category: 'Analgesics / Antipyretic',
    storageType: 'Room Temperature (<30°C)',
    mfgDate: '2024-05-10',
    expiryDate: '2025-05-10',
    batchNo: 'PCM-1008',
    manufacturer: 'Intas Pharmaceuticals',
    quantity: 650,
    unitOriginalPrice: 42,
    concessionPercent: 18,
    hospitalId: 'hosp-3',
    hospitalName: 'Max Super Speciality Hospital',
    location: 'New Delhi, Delhi',
    distanceKm: 22.0,
    dateAdded: '2024-08-20',
    notes: 'High volume standard infusion bottles.',
  }
];

export const INITIAL_REQUESTS = [
  {
    id: 'req-201',
    medicineId: 'med-101',
    medicineName: 'Meropenem Injection 1g IV Vial',
    power: '1g IV Vial',
    quantity: 20,
    unitOriginalPrice: 1850,
    concessionPercent: 35,
    unitFinalPrice: 1202.5,
    totalAmount: 24050,
    fromHospitalId: 'hosp-1',
    fromHospitalName: 'Apollo Hospital',
    toHospitalId: 'hosp-2',
    toHospitalName: 'Fortis Memorial Research Institute',
    requestDate: '2024-08-28T10:30:00Z',
    status: 'accepted',
    rejectReason: null,
    transactionId: 'TXN-984210',
    paymentId: null,
    paymentStatus: 'pending',
    notes: 'Urgent requirement for surgical ICU patients.',
  },
  {
    id: 'req-202',
    medicineId: 'med-102',
    medicineName: 'Enoxaparin Sodium 40mg Prefilled Syringe',
    power: '40mg / 0.4ml',
    quantity: 50,
    unitOriginalPrice: 480,
    concessionPercent: 25,
    unitFinalPrice: 360,
    totalAmount: 18000,
    fromHospitalId: 'hosp-1',
    fromHospitalName: 'Apollo Hospital',
    toHospitalId: 'hosp-3',
    toHospitalName: 'Max Super Speciality Hospital',
    requestDate: '2024-08-25T14:15:00Z',
    status: 'paid',
    rejectReason: null,
    transactionId: 'TXN-773120',
    paymentId: 'pay_Nz8849qK91Xza',
    paymentStatus: 'success',
    paidDate: '2024-08-26T09:45:00Z',
    notes: 'Post-op cardiac recovery unit allocation.',
  },
  {
    id: 'req-203',
    medicineId: 'med-103',
    medicineName: 'Human Albumin 20% 100ml Infusion Bottle',
    power: '100ml Infusion Bottle',
    quantity: 10,
    unitOriginalPrice: 4200,
    concessionPercent: 20,
    unitFinalPrice: 3360,
    totalAmount: 33600,
    fromHospitalId: 'hosp-1',
    fromHospitalName: 'Apollo Hospital',
    toHospitalId: 'hosp-2',
    toHospitalName: 'Fortis Memorial Research Institute',
    requestDate: '2024-08-29T11:00:00Z',
    status: 'pending',
    rejectReason: null,
    transactionId: 'TXN-551982',
    paymentId: null,
    paymentStatus: 'pending',
    notes: 'Emergency liver transplant support reservation.',
  },
  {
    id: 'req-204',
    medicineId: 'med-109',
    medicineName: 'Trastuzumab (Herclon) 440mg',
    power: '440mg Multi-dose Vial',
    quantity: 4,
    unitOriginalPrice: 54000,
    concessionPercent: 20,
    unitFinalPrice: 43200,
    totalAmount: 172800,
    fromHospitalId: 'hosp-1',
    fromHospitalName: 'Apollo Hospital',
    toHospitalId: 'hosp-3',
    toHospitalName: 'Max Super Speciality Hospital',
    requestDate: '2024-08-20T08:30:00Z',
    status: 'rejected',
    rejectReason: 'Requested batch reserved for scheduled chemotherapy sessions in oncology wing.',
    transactionId: 'TXN-331092',
    paymentId: null,
    paymentStatus: 'failed',
    notes: 'Oncology breast cancer protocol batch.',
  },
  // Incoming requests for Apollo (where toHospitalId is 'hosp-1')
  {
    id: 'req-205',
    medicineId: 'med-105',
    medicineName: 'Pantoprazole IV 40mg Vial',
    power: '40mg Vial',
    quantity: 100,
    unitOriginalPrice: 65,
    concessionPercent: 40,
    unitFinalPrice: 39,
    totalAmount: 3900,
    fromHospitalId: 'hosp-2',
    fromHospitalName: 'Fortis Memorial Research Institute',
    toHospitalId: 'hosp-1',
    toHospitalName: 'Apollo Hospital',
    requestDate: '2024-08-30T09:20:00Z',
    status: 'pending',
    rejectReason: null,
    transactionId: 'TXN-881920',
    paymentId: null,
    paymentStatus: 'pending',
    notes: 'Regular replenishment for emergency wards.',
  },
  {
    id: 'req-206',
    medicineId: 'med-106',
    medicineName: 'Insulin Glargine (Lantus) SoloStar',
    power: '3ml SoloStar Pen',
    quantity: 25,
    unitOriginalPrice: 890,
    concessionPercent: 30,
    unitFinalPrice: 623,
    totalAmount: 15575,
    fromHospitalId: 'hosp-3',
    fromHospitalName: 'Max Super Speciality Hospital',
    toHospitalId: 'hosp-1',
    toHospitalName: 'Apollo Hospital',
    requestDate: '2024-08-29T16:40:00Z',
    status: 'pending',
    rejectReason: null,
    transactionId: 'TXN-442819',
    paymentId: null,
    paymentStatus: 'pending',
    notes: 'Endocrinology diabetic patient inpatient supplies.',
  }
];

export const INITIAL_TRACKING = [
  {
    transactionId: 'TXN-773120',
    trackingNumber: 'SMS-EXP-88912',
    senderHospital: 'Max Super Speciality Hospital (Delhi)',
    receiverHospital: 'Apollo Hospital (Mumbai)',
    medicineName: 'Enoxaparin Sodium 40mg',
    quantity: 50,
    status: 'In Transit',
    currentLocation: 'NH-48 Logistic Hub, Vadodara, Gujarat',
    destination: 'Apollo Hospital Central Pharmacy, Belapur, Mumbai',
    eta: 'Today, 06:30 PM (Est. 4 hrs)',
    courierName: 'MediCold Logistics Express Ltd.',
    courierContact: '+91 91234 56789 (Driver: Harpreet Singh)',
    vehicleNo: 'MH-04-AZ-4419 (Temp Controlled)',
    temperature: '4.2°C (Compliant)',
    timeline: [
      { step: 'Order Placed & Verified', date: '2024-08-25 14:15', completed: true, details: 'Verified by SmartMediShare verification engine.' },
      { step: 'Payment Processed via Razorpay', date: '2024-08-26 09:45', completed: true, details: 'Ref: pay_Nz8849qK91Xza, ₹18,000 settled.' },
      { step: 'Dispatched & Cold Seal Applied', date: '2024-08-26 15:30', completed: true, details: 'Dispatched from Saket Hub, Temp: 3.8°C.' },
      { step: 'In Transit with Live IoT GPS/Temp', date: '2024-08-27 11:20', completed: true, details: 'Crossing Vadodara Hub checkpoint.' },
      { step: 'Delivered to Receiving Hospital', date: 'Pending', completed: false, details: 'Target delivery at Mumbai pharmacy intake dock.' },
    ],
    coordinates: {
      origin: [28.5273, 77.2155], // Delhi
      current: [22.3072, 73.1812], // Vadodara
      destination: [19.0144, 73.0408], // Belapur Mumbai
    }
  },
  {
    transactionId: 'TXN-984210',
    trackingNumber: 'SMS-EXP-99210',
    senderHospital: 'Fortis Memorial Research Institute',
    receiverHospital: 'Apollo Hospital',
    medicineName: 'Meropenem Injection 1g IV',
    quantity: 20,
    status: 'Ordered',
    currentLocation: 'Fortis Gurgaon Warehouse Dispatch Dock',
    destination: 'Apollo Hospital Mumbai',
    eta: 'Tomorrow, 02:00 PM',
    courierName: 'BlueDart Bio-Express',
    courierContact: '+91 98888 12345',
    vehicleNo: 'HR-26-CD-9012',
    temperature: '3.5°C',
    timeline: [
      { step: 'Order Placed & Verified', date: '2024-08-28 10:30', completed: true, details: 'Exchange terms accepted by Fortis.' },
      { step: 'Awaiting Payment Settlement', date: '2024-08-28 11:00', completed: false, details: 'Pending buyer payment authorization.' },
      { step: 'Dispatched & Cold Seal Applied', date: 'Pending', completed: false, details: 'Packaging in insulated dry ice container.' },
      { step: 'In Transit', date: 'Pending', completed: false, details: 'Flight cargo scheduled from DEL to BOM.' },
      { step: 'Delivered', date: 'Pending', completed: false, details: 'Dock inspection required.' },
    ],
    coordinates: {
      origin: [28.4595, 77.0266], // Gurgaon
      current: [28.4595, 77.0266],
      destination: [19.0144, 73.0408],
    }
  }
];

export const INITIAL_PAYMENTS = [
  {
    id: 'pay-001',
    transactionId: 'TXN-773120',
    medicineName: 'Enoxaparin Sodium 40mg Prefilled Syringe',
    quantity: 50,
    amount: 18000,
    gstAmount: 2160,
    totalPaid: 20160,
    paymentStatus: 'Success',
    date: '2024-08-26 09:45 AM',
    razorpayPaymentId: 'pay_Nz8849qK91Xza',
    razorpayOrderId: 'order_Nx7712398a',
    paymentMethod: 'UPI / Razorpay Business (HDFC)',
    buyerHospital: 'Apollo Hospital (Mumbai)',
    sellerHospital: 'Max Super Speciality Hospital (Delhi)',
  },
  {
    id: 'pay-002',
    transactionId: 'TXN-661209',
    medicineName: 'Human Albumin 20% 100ml Infusion',
    quantity: 15,
    amount: 50400,
    gstAmount: 6048,
    totalPaid: 56448,
    paymentStatus: 'Success',
    date: '2024-08-14 03:20 PM',
    razorpayPaymentId: 'pay_My9921bK44Pqm',
    razorpayOrderId: 'order_Mx5544123b',
    paymentMethod: 'Corporate NetBanking (ICICI)',
    buyerHospital: 'Apollo Hospital (Mumbai)',
    sellerHospital: 'Fortis Memorial Research Institute',
  },
  {
    id: 'pay-003',
    transactionId: 'TXN-331092',
    medicineName: 'Trastuzumab (Herclon) 440mg',
    quantity: 4,
    amount: 172800,
    gstAmount: 20736,
    totalPaid: 193536,
    paymentStatus: 'Failed',
    date: '2024-08-20 08:45 AM',
    razorpayPaymentId: 'pay_Kx1198fL00Rrr',
    razorpayOrderId: 'order_Kx1122334c',
    paymentMethod: 'Bank Wire Transfer',
    buyerHospital: 'Apollo Hospital (Mumbai)',
    sellerHospital: 'Max Super Speciality Hospital',
  },
  {
    id: 'pay-004',
    transactionId: 'TXN-984210',
    medicineName: 'Meropenem Injection 1g IV Vial',
    quantity: 20,
    amount: 24050,
    gstAmount: 2886,
    totalPaid: 26936,
    paymentStatus: 'Pending',
    date: '2024-08-28 10:35 AM',
    razorpayPaymentId: 'Awaiting Initiation',
    razorpayOrderId: 'order_Ot9944111d',
    paymentMethod: 'Pending Checkout',
    buyerHospital: 'Apollo Hospital (Mumbai)',
    sellerHospital: 'Fortis Memorial Research Institute',
  },
  {
    id: 'pay-005',
    transactionId: 'TXN-672418',
    medicineName: 'Ceftriaxone Sodium 1g Injection',
    quantity: 80,
    amount: 18400,
    gstAmount: 2208,
    totalPaid: 20608,
    paymentStatus: 'Success',
    date: '2024-08-27 02:15 PM',
    razorpayPaymentId: 'pay_Px8832cL17Taa',
    razorpayOrderId: 'order_Px5588214b',
    paymentMethod: 'Razorpay Escrow Settlement',
    buyerHospital: 'Fortis Memorial Research Institute',
    sellerHospital: 'Apollo Hospital (Mumbai)',
  },
  {
    id: 'pay-006',
    transactionId: 'TXN-718305',
    medicineName: 'Vancomycin Hydrochloride 500mg Vial',
    quantity: 30,
    amount: 12600,
    gstAmount: 1512,
    totalPaid: 14112,
    paymentStatus: 'Success',
    date: '2024-08-22 11:05 AM',
    razorpayPaymentId: 'pay_Qx4417dM29Kbb',
    razorpayOrderId: 'order_Qx3309127c',
    paymentMethod: 'Corporate NetBanking (ICICI)',
    buyerHospital: 'Max Super Speciality Hospital (Delhi)',
    sellerHospital: 'Apollo Hospital (Mumbai)',
  }
];

export const INITIAL_DISPOSALS = [
  {
    id: 'disp-301',
    hospitalName: 'Apollo Hospital',
    medicineName: 'Cefotaxime Sodium 500mg (Expired)',
    batchNo: 'CF500-112',
    quantity: '150 Vials (12.5 kg)',
    expiryDate: '2024-06-30',
    bioCentreName: 'Maharashtra Enviro Power Bio-Medical Waste Plant',
    vehicleNo: 'MH-04-GP-8833',
    driverContact: '+91 97654 32109 (Mahesh K.)',
    currentLocation: 'Taloja MIDC Highway, Navi Mumbai',
    eta: 'Completed (Incineration Done)',
    status: 'Incinerated & Certified',
    certificateNo: 'BMW-INC-2024-88712',
  },
  {
    id: 'disp-302',
    hospitalName: 'Max Super Speciality Hospital',
    medicineName: 'Oxytocin Injection 10 IU (Compromised Cold Chain)',
    batchNo: 'OXY-908',
    quantity: '80 Ampoules (3.2 kg)',
    expiryDate: '2024-07-15',
    bioCentreName: 'Delhi Central Bio-Medical Incinerator, Okhla',
    vehicleNo: 'DL-01-EA-5541',
    driverContact: '+91 98100 45678 (Suresh Pal)',
    currentLocation: 'Mathura Road Transit Hub',
    eta: 'Today, 05:00 PM (In Transit)',
    status: 'In Transit to Bio-Centre',
    certificateNo: 'Pending Incineration',
  },
  {
    id: 'disp-303',
    hospitalName: 'Fortis Memorial Research Institute',
    medicineName: 'Chemotherapy Cisplatin Residues (Damaged)',
    batchNo: 'CIS-4410',
    quantity: '18 Vials Hazardous Cytotoxic (4.0 kg)',
    expiryDate: '2024-07-31',
    bioCentreName: 'Haryana State Bio-Hazard Incineration Facility',
    vehicleNo: 'HR-55-ZX-9922',
    driverContact: '+91 99912 34567 (Joginder Singh)',
    currentLocation: 'Fortis Basement Bio-Waste Holding Cell',
    eta: 'Scheduled Pickup: Tomorrow 10:00 AM',
    status: 'Pending Pickup',
    certificateNo: 'Scheduled',
  }
];

export const INITIAL_FEEDBACKS = [
  {
    id: 'fb-401',
    hospitalId: 'hosp-2',
    hospitalName: 'Fortis Memorial Research Institute',
    rating: 5,
    category: 'Logistics & Cold-Chain',
    feedbackText: 'The cold chain validation and real-time temperature loggers on SmartMediShare are extraordinary. Saved over ₹3.4 Lakhs on near-expiry oncology supplies.',
    date: '2024-08-27',
    adminReply: 'Thank you Dr. Deshmukh. Our temperature telemetry integration ensures zero spoilage during transport.',
    repliedDate: '2024-08-28',
  },
  {
    id: 'fb-402',
    hospitalId: 'hosp-3',
    hospitalName: 'Max Super Speciality Hospital',
    rating: 4,
    category: 'Inventory Concession Calculator',
    feedbackText: 'The automated concession calculator based on shelf-life months is very intuitive. Would love an option to auto-match bulk buyers in neighbouring districts.',
    date: '2024-08-25',
    adminReply: 'Appreciate your feedback! District-level automated smart matching is rolling out in next sprint.',
    repliedDate: '2024-08-26',
  },
  {
    id: 'fb-403',
    hospitalId: 'hosp-1',
    hospitalName: 'Apollo Hospital',
    rating: 5,
    category: 'Platform Verification & Security',
    feedbackText: 'Fast onboarding and seamless Razorpay mock gateway testing. The compliance documentation audit gives complete peace of mind for Schedule H drugs.',
    date: '2024-08-29',
    adminReply: null,
    repliedDate: null,
  }
];

export const HOSPITAL_ANALYTICS = {
  stats: {
    totalMedicines: 184,
    monthlyPurchases: 462500,
    monthlySales: 689000,
    profitabilityPercent: 28.4,
    medicinesSaved: 1420,
    activeTransfers: 3,
  },
  purchasesMonthly: [
    { month: 'Mar', amount: 320000, units: 140 },
    { month: 'Apr', amount: 410000, units: 185 },
    { month: 'May', amount: 380000, units: 160 },
    { month: 'Jun', amount: 490000, units: 210 },
    { month: 'Jul', amount: 440000, units: 195 },
    { month: 'Aug', amount: 462500, units: 205 },
  ],
  salesMonthly: [
    { month: 'Mar', amount: 480000, units: 220 },
    { month: 'Apr', amount: 530000, units: 245 },
    { month: 'May', amount: 590000, units: 280 },
    { month: 'Jun', amount: 620000, units: 290 },
    { month: 'Jul', amount: 645000, units: 310 },
    { month: 'Aug', amount: 689000, units: 340 },
  ],
  profitabilityTrend: [
    { month: 'Apr', revenue: 530000, cost: 410000, marginPercent: 22.6 },
    { month: 'May', revenue: 590000, cost: 380000, marginPercent: 35.5 },
    { month: 'Jun', revenue: 620000, cost: 490000, marginPercent: 20.9 },
    { month: 'Jul', revenue: 645000, cost: 440000, marginPercent: 31.7 },
    { month: 'Aug', revenue: 689000, cost: 462500, marginPercent: 32.8 },
  ]
};

export const ADMIN_ANALYTICS = {
  stats: {
    totalHospitals: 48,
    monthlyTransfers: 324,
    totalMedicinesTransferred: 18450,
    totalPlatformVolume: '₹ 1.84 Cr',
    wastagePreventedTons: '14.2 Tons',
    avgFulfillmentRate: '98.4%',
  },
  transferTrends: [
    { month: 'Mar', transfers: 180, volumeINR: 980000 },
    { month: 'Apr', transfers: 220, volumeINR: 1250000 },
    { month: 'May', transfers: 260, volumeINR: 1480000 },
    { month: 'Jun', transfers: 290, volumeINR: 1620000 },
    { month: 'Jul', transfers: 310, volumeINR: 1740000 },
    { month: 'Aug', transfers: 324, volumeINR: 1840000 },
  ],
  systemPerformance: [
    { metric: 'Fulfillment Rate', score: 98.4, target: 95 },
    { metric: 'Cold-Chain Integrity', score: 99.1, target: 98 },
    { metric: 'Avg Transit Speed (h)', score: 92.5, target: 90 },
    { metric: 'Verification Turnaround', score: 96.0, target: 90 },
    { metric: 'Disposal Compliance', score: 100.0, target: 100 },
  ],
  topHotMedicines: [
    { name: 'Meropenem 1g', exchanges: 420, valueLakhs: 7.77 },
    { name: 'Enoxaparin 40mg', exchanges: 390, valueLakhs: 1.87 },
    { name: 'Human Albumin 20%', exchanges: 310, valueLakhs: 13.02 },
    { name: 'Remdesivir 100mg', exchanges: 280, valueLakhs: 7.84 },
    { name: 'Augmentin 625mg', exchanges: 240, valueLakhs: 0.50 },
    { name: 'Pantoprazole 40mg', exchanges: 215, valueLakhs: 0.14 },
    { name: 'Trastuzumab 440mg', exchanges: 195, valueLakhs: 105.3 },
    { name: 'Insulin Glargine', exchanges: 180, valueLakhs: 1.60 },
    { name: 'Ceftriaxone 1g', exchanges: 165, valueLakhs: 0.12 },
    { name: 'Noradrenaline 2mg', exchanges: 150, valueLakhs: 0.28 },
  ]
};
